// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindAdminSSO = `-- name: BindAdminSSO :one
UPDATE admins
SET idp_subject   = $2,
    idp_config_id = $3,
    sso_bound     = true
WHERE id          = $1
  AND revoked_at  IS NULL
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

type BindAdminSSOParams struct {
	ID          uuid.UUID   `json:"id"`
	IdpSubject  pgtype.Text `json:"idp_subject"`
	IdpConfigID pgtype.UUID `json:"idp_config_id"`
}

// Called once during SSO binding confirmation flow.
// Stores sub claim, links IdP config, marks sso_bound.
func (q *Queries) BindAdminSSO(ctx context.Context, arg BindAdminSSOParams) (Admin, error) {
	row := q.db.QueryRow(ctx, bindAdminSSO, arg.ID, arg.IdpSubject, arg.IdpConfigID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const countOwnersByOrg = `-- name: CountOwnersByOrg :one
SELECT COUNT(*) FROM admins
WHERE org_id     = $1
  AND role       = 'owner'
  AND revoked_at IS NULL
`

// Used before revoking an owner — must always have at least one.
func (q *Queries) CountOwnersByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminByIDPSubject = `-- name: GetAdminByIDPSubject :one

SELECT id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at FROM admins
WHERE org_id      = $1
  AND idp_subject = $2
  AND revoked_at  IS NULL
`

type GetAdminByIDPSubjectParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	IdpSubject pgtype.Text `json:"idp_subject"`
}

// =================================================================
// ADMINS
// =================================================================
// Used at OIDC callback. Matches on permanent IdP sub claim.
func (q *Queries) GetAdminByIDPSubject(ctx context.Context, arg GetAdminByIDPSubjectParams) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByIDPSubject, arg.OrgID, arg.IdpSubject)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAdminsByOrg = `-- name: ListAdminsByOrg :many
SELECT id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at FROM admins
WHERE org_id     = $1
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListAdminsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdminsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.PasswordHash,
			&i.IdpSubject,
			&i.IdpConfigID,
			&i.SsoBound,
			&i.SsoOnly,
			&i.OtpSecret,
			&i.OtpEnabled,
			&i.IsActive,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateAdminToSSOOnly = `-- name: MigrateAdminToSSOOnly :one
UPDATE admins
SET password_hash = NULL,
    sso_only      = true
WHERE id          = $1
  AND sso_bound   = true
  AND revoked_at  IS NULL
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

// Called after owner confirms SSO migration.
// Clears password_hash — no going back without owner action.
func (q *Queries) MigrateAdminToSSOOnly(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, migrateAdminToSSOOnly, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAdmin = `-- name: RevokeAdmin :one
UPDATE admins
SET revoked_at = now()
WHERE id         = $1
  AND revoked_at IS NULL
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

func (q *Queries) RevokeAdmin(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, revokeAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateAdminRole = `-- name: UpdateAdminRole :one
UPDATE admins
SET role = $2
WHERE id         = $1
  AND revoked_at IS NULL
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

type UpdateAdminRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

// Owner only action.
func (q *Queries) UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) (Admin, error) {
	row := q.db.QueryRow(ctx, updateAdminRole, arg.ID, arg.Role)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
