// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one

INSERT INTO apps (org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at
`

type CreateAppParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	ConnectorID pgtype.UUID `json:"connector_id"`
	Name        string      `json:"name"`
	Subdomain   string      `json:"subdomain"`
	Upstream    string      `json:"upstream"`
	Protocol    string      `json:"protocol"`
	IsPublic    bool        `json:"is_public"`
	SockPass    string      `json:"sock_pass"`
}

// =================================================================
// APPS
// =================================================================
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.OrgID,
		arg.ConnectorID,
		arg.Name,
		arg.Subdomain,
		arg.Upstream,
		arg.Protocol,
		arg.IsPublic,
		arg.SockPass,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectorID,
		&i.Name,
		&i.Subdomain,
		&i.Upstream,
		&i.Protocol,
		&i.IsPublic,
		&i.SockPass,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :one
UPDATE apps
SET deleted_at = now()
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
RETURNING id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at
`

type DeleteAppParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Soft delete. Policies referencing this app remain for audit history.
func (q *Queries) DeleteApp(ctx context.Context, arg DeleteAppParams) (App, error) {
	row := q.db.QueryRow(ctx, deleteApp, arg.ID, arg.OrgID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectorID,
		&i.Name,
		&i.Subdomain,
		&i.Upstream,
		&i.Protocol,
		&i.IsPublic,
		&i.SockPass,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at FROM apps
WHERE id         = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAppByID(ctx context.Context, id uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectorID,
		&i.Name,
		&i.Subdomain,
		&i.Upstream,
		&i.Protocol,
		&i.IsPublic,
		&i.SockPass,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppByIDAndOrg = `-- name: GetAppByIDAndOrg :one
SELECT id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at FROM apps
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
`

type GetAppByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAppByIDAndOrg(ctx context.Context, arg GetAppByIDAndOrgParams) (App, error) {
	row := q.db.QueryRow(ctx, getAppByIDAndOrg, arg.ID, arg.OrgID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectorID,
		&i.Name,
		&i.Subdomain,
		&i.Upstream,
		&i.Protocol,
		&i.IsPublic,
		&i.SockPass,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppBySubdomain = `-- name: GetAppBySubdomain :one
SELECT id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at FROM apps
WHERE org_id     = $1
  AND subdomain  = $2
  AND deleted_at IS NULL
`

type GetAppBySubdomainParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	Subdomain string    `json:"subdomain"`
}

// Called by Gateway to resolve subdomain to app during routing.
func (q *Queries) GetAppBySubdomain(ctx context.Context, arg GetAppBySubdomainParams) (App, error) {
	row := q.db.QueryRow(ctx, getAppBySubdomain, arg.OrgID, arg.Subdomain)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectorID,
		&i.Name,
		&i.Subdomain,
		&i.Upstream,
		&i.Protocol,
		&i.IsPublic,
		&i.SockPass,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAppsByConnector = `-- name: ListAppsByConnector :many
SELECT id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at FROM apps
WHERE connector_id = $1
  AND deleted_at   IS NULL
`

func (q *Queries) ListAppsByConnector(ctx context.Context, connectorID pgtype.UUID) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsByConnector, connectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectorID,
			&i.Name,
			&i.Subdomain,
			&i.Upstream,
			&i.Protocol,
			&i.IsPublic,
			&i.SockPass,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOrg = `-- name: ListAppsByOrg :many
SELECT id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at FROM apps
WHERE org_id     = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListAppsByOrg(ctx context.Context, orgID uuid.UUID) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectorID,
			&i.Name,
			&i.Subdomain,
			&i.Upstream,
			&i.Protocol,
			&i.IsPublic,
			&i.SockPass,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :one
UPDATE apps
SET name         = $3,
    subdomain    = $4,
    upstream     = $5,
    protocol     = $6,
    is_public    = $7,
    connector_id = $8,
    sock_pass = $9
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
RETURNING id, org_id, connector_id, name, subdomain, upstream, protocol, is_public, sock_pass, created_at, deleted_at
`

type UpdateAppParams struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       uuid.UUID   `json:"org_id"`
	Name        string      `json:"name"`
	Subdomain   string      `json:"subdomain"`
	Upstream    string      `json:"upstream"`
	Protocol    string      `json:"protocol"`
	IsPublic    bool        `json:"is_public"`
	ConnectorID pgtype.UUID `json:"connector_id"`
	SockPass    string      `json:"sock_pass"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Subdomain,
		arg.Upstream,
		arg.Protocol,
		arg.IsPublic,
		arg.ConnectorID,
		arg.SockPass,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectorID,
		&i.Name,
		&i.Subdomain,
		&i.Upstream,
		&i.Protocol,
		&i.IsPublic,
		&i.SockPass,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
