// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateAdmin = `-- name: ActivateAdmin :one
UPDATE admins
SET org_id = $2,
    is_active = TRUE
WHERE id = $1
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

type ActivateAdminParams struct {
	ID    uuid.UUID   `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// Called at the end of /verify-otp during setup. Creates the org and links it.
func (q *Queries) ActivateAdmin(ctx context.Context, arg ActivateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, activateAdmin, arg.ID, arg.OrgID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAdmin = `-- name: CreateAdmin :one

INSERT INTO admins (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

type CreateAdminParams struct {
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Role         string      `json:"role"`
}

// =================================================================
// AUTH
// =================================================================
func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash, arg.Role)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, admin_id, token_hash, expires_at, used_at
`

type CreatePasswordResetTokenParams struct {
	AdminID   uuid.UUID `json:"admin_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO admin_sessions (admin_id, org_id, refresh_token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, admin_id, org_id, refresh_token, expires_at, created_at, revoked_at
`

type CreateSessionParams struct {
	AdminID      uuid.UUID `json:"admin_id"`
	OrgID        uuid.UUID `json:"org_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AdminID,
		arg.OrgID,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.OrgID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createSetupToken = `-- name: CreateSetupToken :one
INSERT INTO admin_setup_tokens (admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, admin_id, token_hash, expires_at, used_at
`

type CreateSetupTokenParams struct {
	AdminID   uuid.UUID `json:"admin_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSetupToken(ctx context.Context, arg CreateSetupTokenParams) (AdminSetupToken, error) {
	row := q.db.QueryRow(ctx, createSetupToken, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	var i AdminSetupToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions
WHERE expires_at < now()
   OR revoked_at IS NOT NULL
`

// Housekeeping. Run periodically via background job.
func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at FROM admins
WHERE email   = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminByEmailWithOrg = `-- name: GetAdminByEmailWithOrg :one
SELECT id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at FROM admins
WHERE org_id = $1
  AND email   = $2
  AND revoked_at IS NULL
`

type GetAdminByEmailWithOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Email string      `json:"email"`
}

// Used at password login. Returns record regardless of sso_only
// so caller can check sso_only and reject if needed.
func (q *Queries) GetAdminByEmailWithOrg(ctx context.Context, arg GetAdminByEmailWithOrgParams) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmailWithOrg, arg.OrgID, arg.Email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at FROM admins
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT id, admin_id, org_id, refresh_token, expires_at, created_at, revoked_at FROM admin_sessions
WHERE refresh_token = $1
  AND expires_at  > now()
  AND revoked_at  IS NULL
`

// Hot path: called on every dashboard request.
// Returns session only if valid (not expired, not revoked).
func (q *Queries) GetAdminSession(ctx context.Context, refreshToken string) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSession, refreshToken)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.OrgID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, admin_id, token_hash, expires_at, used_at FROM password_reset_tokens
WHERE token_hash = $1
    AND used_at IS NULL
    AND expires_at > NOW()
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getSetupToken = `-- name: GetSetupToken :one
SELECT id, admin_id, token_hash, expires_at, used_at FROM admin_setup_tokens
WHERE token_hash = $1
    AND used_at IS NULL
    AND expires_at > NOW()
`

func (q *Queries) GetSetupToken(ctx context.Context, tokenHash string) (AdminSetupToken, error) {
	row := q.db.QueryRow(ctx, getSetupToken, tokenHash)
	var i AdminSetupToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	return err
}

const markSetupTokenUsed = `-- name: MarkSetupTokenUsed :exec
UPDATE admin_setup_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkSetupTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSetupTokenUsed, id)
	return err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions
SET revoked_at = now()
WHERE id         = $1
  AND revoked_at IS NULL
`

// Single session revocation (logout).
func (q *Queries) RevokeAdminSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, id)
	return err
}

const revokeAllAdminSessionsForAdmin = `-- name: RevokeAllAdminSessionsForAdmin :exec
UPDATE admin_sessions
SET revoked_at = now()
WHERE admin_id   = $1
  AND revoked_at IS NULL
`

// Revoke all sessions for an admin (e.g. role changed, account suspended, passchange/account compromise).
func (q *Queries) RevokeAllAdminSessionsForAdmin(ctx context.Context, adminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAdminSessionsForAdmin, adminID)
	return err
}

const revokeAllAdminSessionsForOrg = `-- name: RevokeAllAdminSessionsForOrg :exec
UPDATE admin_sessions
SET revoked_at = now()
WHERE org_id     = $1
  AND revoked_at IS NULL
`

// Nuclear option — used when org SSO config changes.
func (q *Queries) RevokeAllAdminSessionsForOrg(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAdminSessionsForOrg, orgID)
	return err
}

const updateAdminOTP = `-- name: UpdateAdminOTP :one
UPDATE admins
SET otp_secret = $2,
    otp_enabled = $3
WHERE id = $1
RETURNING id, org_id, email, password_hash, idp_subject, idp_config_id, sso_bound, sso_only, otp_secret, otp_enabled, is_active, role, invited_by, created_at, revoked_at
`

type UpdateAdminOTPParams struct {
	ID         uuid.UUID   `json:"id"`
	OtpSecret  pgtype.Text `json:"otp_secret"`
	OtpEnabled bool        `json:"otp_enabled"`
}

func (q *Queries) UpdateAdminOTP(ctx context.Context, arg UpdateAdminOTPParams) (Admin, error) {
	row := q.db.QueryRow(ctx, updateAdminOTP, arg.ID, arg.OtpSecret, arg.OtpEnabled)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.IdpSubject,
		&i.IdpConfigID,
		&i.SsoBound,
		&i.SsoOnly,
		&i.OtpSecret,
		&i.OtpEnabled,
		&i.IsActive,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins
SET password_hash = $2
WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}
