// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForBulkCreateAccessLogs implements pgx.CopyFromSource.
type iteratorForBulkCreateAccessLogs struct {
	rows                 []BulkCreateAccessLogsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateAccessLogs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateAccessLogs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrgID,
		r.rows[0].AppID,
		r.rows[0].IdpConfigID,
		r.rows[0].UserEmail,
		r.rows[0].Method,
		r.rows[0].Path,
		r.rows[0].Status,
		r.rows[0].LatencyMs,
		r.rows[0].Ip,
		r.rows[0].Result,
		r.rows[0].DenyReason,
	}, nil
}

func (r iteratorForBulkCreateAccessLogs) Err() error {
	return nil
}

// Uses pgx COPY protocol for high-throughput batch inserts.
// Gateway drains its local buffer to CP every 10s.
func (q *Queries) BulkCreateAccessLogs(ctx context.Context, arg []BulkCreateAccessLogsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"access_logs"}, []string{"org_id", "app_id", "idp_config_id", "user_email", "method", "path", "status", "latency_ms", "ip", "result", "deny_reason"}, &iteratorForBulkCreateAccessLogs{rows: arg})
}
