// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_events.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const ackGatewayEvents = `-- name: AckGatewayEvents :exec
UPDATE gateway_events_acks
SET
    last_acked_seq = GREATEST(
        last_acked_seq,
        $2
    ),
    updated_at = NOW()
WHERE gateway_id = $1
`

type AckGatewayEventsParams struct {
	GatewayID    uuid.UUID `json:"gateway_id"`
	LastAckedSeq int64     `json:"last_acked_seq"`
}

func (q *Queries) AckGatewayEvents(ctx context.Context, arg AckGatewayEventsParams) error {
	_, err := q.db.Exec(ctx, ackGatewayEvents, arg.GatewayID, arg.LastAckedSeq)
	return err
}

const allocateGatewayEventSeq = `-- name: AllocateGatewayEventSeq :one
INSERT INTO gateway_event_sequences (
    gateway_id,
    next_seq
)
VALUES ($1, 2)
ON CONFLICT (gateway_id)
DO UPDATE
SET next_seq = gateway_event_sequences.next_seq + 1
RETURNING next_seq - 1 AS seq
`

func (q *Queries) AllocateGatewayEventSeq(ctx context.Context, gatewayID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, allocateGatewayEventSeq, gatewayID)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const deleteAckedGatewayEvents = `-- name: DeleteAckedGatewayEvents :exec
DELETE FROM gateway_events ge
USING gateway_events_acks ack
WHERE ge.gateway_id = ack.gateway_id
  AND ge.seq <= ack.last_acked_seq
  AND ge.created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteAckedGatewayEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAckedGatewayEvents)
	return err
}

const getLastAckedSeqForGateway = `-- name: GetLastAckedSeqForGateway :one
SELECT last_acked_seq
FROM gateway_events_acks
WHERE gateway_id = $1
`

func (q *Queries) GetLastAckedSeqForGateway(ctx context.Context, gatewayID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLastAckedSeqForGateway, gatewayID)
	var last_acked_seq int64
	err := row.Scan(&last_acked_seq)
	return last_acked_seq, err
}

const getLatestGatewayEventSeq = `-- name: GetLatestGatewayEventSeq :one
SELECT COALESCE(MAX(seq), 0)::BIGINT
FROM gateway_events
WHERE gateway_id = $1
`

func (q *Queries) GetLatestGatewayEventSeq(ctx context.Context, gatewayID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestGatewayEventSeq, gatewayID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertGatewayEvent = `-- name: InsertGatewayEvent :exec
INSERT INTO gateway_events (
    gateway_id,
    seq,
    event_id,
    command,
    delivery_mode,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertGatewayEventParams struct {
	GatewayID    uuid.UUID       `json:"gateway_id"`
	Seq          int64           `json:"seq"`
	EventID      uuid.UUID       `json:"event_id"`
	Command      string          `json:"command"`
	DeliveryMode string          `json:"delivery_mode"`
	Payload      json.RawMessage `json:"payload"`
}

func (q *Queries) InsertGatewayEvent(ctx context.Context, arg InsertGatewayEventParams) error {
	_, err := q.db.Exec(ctx, insertGatewayEvent,
		arg.GatewayID,
		arg.Seq,
		arg.EventID,
		arg.Command,
		arg.DeliveryMode,
		arg.Payload,
	)
	return err
}

const listGatewayEventsAfter = `-- name: ListGatewayEventsAfter :many
SELECT
    gateway_id,
    seq,
    event_id,
    command,
    delivery_mode,
    payload,
    created_at
FROM gateway_events
WHERE gateway_id = $1
  AND seq > $2
ORDER BY seq ASC
`

type ListGatewayEventsAfterParams struct {
	GatewayID uuid.UUID `json:"gateway_id"`
	Seq       int64     `json:"seq"`
}

func (q *Queries) ListGatewayEventsAfter(ctx context.Context, arg ListGatewayEventsAfterParams) ([]GatewayEvent, error) {
	rows, err := q.db.Query(ctx, listGatewayEventsAfter, arg.GatewayID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayEvent{}
	for rows.Next() {
		var i GatewayEvent
		if err := rows.Scan(
			&i.GatewayID,
			&i.Seq,
			&i.EventID,
			&i.Command,
			&i.DeliveryMode,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
