// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateways_connectors.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConnector = `-- name: CreateConnector :one

INSERT INTO connectors (org_id, gateway_id, name, token_hash, open_sock)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at
`

type CreateConnectorParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
	OpenSock  bool      `json:"open_sock"`
}

// =================================================================
// CONNECTORS
// token_hash: SHA-256 of connector enrollment token.
// =================================================================
func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, createConnector,
		arg.OrgID,
		arg.GatewayID,
		arg.Name,
		arg.TokenHash,
		arg.OpenSock,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const createGateway = `-- name: CreateGateway :one

WITH new_gateway AS (
    INSERT INTO gateways (
        org_id, 
        name, 
        deployment_type, 
        token_hash, 
        public_url, 
        ip_address,
        log_to_cp
    )
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
),
init_sequence AS (
    INSERT INTO gateway_event_sequences (gateway_id)
    SELECT id FROM new_gateway
    ON CONFLICT DO NOTHING
),
init_acks AS (
    INSERT INTO gateway_events_acks (gateway_id)
    SELECT id FROM new_gateway
    ON CONFLICT DO NOTHING
)
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM new_gateway
`

type CreateGatewayParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	DeploymentType string    `json:"deployment_type"`
	TokenHash      string    `json:"token_hash"`
	PublicUrl      string    `json:"public_url"`
	IpAddress      string    `json:"ip_address"`
	LogToCp        bool      `json:"log_to_cp"`
}

type CreateGatewayRow struct {
	ID             uuid.UUID          `json:"id"`
	OrgID          uuid.UUID          `json:"org_id"`
	Name           string             `json:"name"`
	TokenHash      string             `json:"token_hash"`
	Version        pgtype.Text        `json:"version"`
	DeploymentType string             `json:"deployment_type"`
	PublicUrl      string             `json:"public_url"`
	QuicPort       pgtype.Text        `json:"quic_port"`
	GrpcPort       pgtype.Text        `json:"grpc_port"`
	HttpsPort      pgtype.Text        `json:"https_port"`
	IpAddress      string             `json:"ip_address"`
	LastHeartbeat  pgtype.Timestamptz `json:"last_heartbeat"`
	Status         string             `json:"status"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      time.Time          `json:"created_at"`
	LogToCp        bool               `json:"log_to_cp"`
	Uptime         int64              `json:"uptime"`
	EnrolledAt     pgtype.Timestamptz `json:"enrolled_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

// =================================================================
// GATEWAYS
// token_hash: SHA-256 of enrollment token. Never plaintext.
// =================================================================
func (q *Queries) CreateGateway(ctx context.Context, arg CreateGatewayParams) (CreateGatewayRow, error) {
	row := q.db.QueryRow(ctx, createGateway,
		arg.OrgID,
		arg.Name,
		arg.DeploymentType,
		arg.TokenHash,
		arg.PublicUrl,
		arg.IpAddress,
		arg.LogToCp,
	)
	var i CreateGatewayRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const enrollConnector = `-- name: EnrollConnector :one
UPDATE connectors 
SET enrolled_at = NOW(), 
    status = 'connected',
    is_active = true,
    last_seen = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at
`

func (q *Queries) EnrollConnector(ctx context.Context, tokenHash string) (Connector, error) {
	row := q.db.QueryRow(ctx, enrollConnector, tokenHash)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const enrollGateway = `-- name: EnrollGateway :one
UPDATE gateways 
SET enrolled_at = NOW(), 
    status = 'healthy',
    last_heartbeat = NOW()
WHERE token_hash = $1
  AND is_active = true
  AND revoked_at IS NULL
RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
`

func (q *Queries) EnrollGateway(ctx context.Context, tokenHash string) (Gateway, error) {
	row := q.db.QueryRow(ctx, enrollGateway, tokenHash)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveConnectorByID = `-- name: GetActiveConnectorByID :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at FROM connectors
WHERE id         = $1
  AND is_active = true
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error) {
	row := q.db.QueryRow(ctx, getActiveConnectorByID, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveGatewayByID = `-- name: GetActiveGatewayByID :one
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM gateways
WHERE id         = $1
  AND is_active = true
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveGatewayByID(ctx context.Context, id uuid.UUID) (Gateway, error) {
	row := q.db.QueryRow(ctx, getActiveGatewayByID, id)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConnectorByID = `-- name: GetConnectorByID :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at FROM connectors
WHERE id         = $1
`

func (q *Queries) GetConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByID, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConnectorByIDAndOrg = `-- name: GetConnectorByIDAndOrg :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at FROM connectors
WHERE id         = $1
  AND org_id     = $2
`

type GetConnectorByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetConnectorByIDAndOrg(ctx context.Context, arg GetConnectorByIDAndOrgParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByIDAndOrg, arg.ID, arg.OrgID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConnectorByTokenHash = `-- name: GetConnectorByTokenHash :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at FROM connectors
WHERE token_hash = $1
  AND status = 'pending'
  AND is_active = true
  AND revoked_at IS NULL
`

// Called on connector → gateway auth.
func (q *Queries) GetConnectorByTokenHash(ctx context.Context, tokenHash string) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByTokenHash, tokenHash)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGatewayByID = `-- name: GetGatewayByID :one
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM gateways
WHERE id         = $1
`

func (q *Queries) GetGatewayByID(ctx context.Context, id uuid.UUID) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByID, id)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGatewayByIDAndOrg = `-- name: GetGatewayByIDAndOrg :one
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM gateways
WHERE id         = $1
  AND org_id     = $2
  AND is_active = true
  AND revoked_at IS NULL
`

type GetGatewayByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetGatewayByIDAndOrg(ctx context.Context, arg GetGatewayByIDAndOrgParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByIDAndOrg, arg.ID, arg.OrgID)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGatewayByTokenHash = `-- name: GetGatewayByTokenHash :one
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM gateways
WHERE token_hash = $1
  AND status = 'pending'
  AND is_active = true
  AND revoked_at IS NULL
`

// Called on every Gateway → CP request (heartbeat, policy sync).
// Keep this fast — it is on the service path.
func (q *Queries) GetGatewayByTokenHash(ctx context.Context, tokenHash string) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByTokenHash, tokenHash)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveConnectorsByGateway = `-- name: ListActiveConnectorsByGateway :many
SELECT c.id, c.org_id, c.gateway_id, c.name, c.token_hash, c.last_seen, c.status, c.created_at, c.is_active, c.open_sock, c.active_streams, c.enrolled_at, c.revoked_at
FROM connectors c
WHERE c.gateway_id = $1
  AND c.is_active = true
  AND c.revoked_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM component_certificates cc
      WHERE cc.component_id = c.id
        AND cc.component_type = 'connector'
        AND cc.revoked_at IS NULL
        AND cc.expires_at > NOW()
  )
`

// Called on gateway → connector auth.
func (q *Queries) ListActiveConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listActiveConnectorsByGateway, gatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GatewayID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeen,
			&i.Status,
			&i.CreatedAt,
			&i.IsActive,
			&i.OpenSock,
			&i.ActiveStreams,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGatewaysByOrg = `-- name: ListActiveGatewaysByOrg :many
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM gateways
WHERE org_id = $1
AND is_active = true
ORDER BY created_at ASC
`

func (q *Queries) ListActiveGatewaysByOrg(ctx context.Context, orgID uuid.UUID) ([]Gateway, error) {
	rows, err := q.db.Query(ctx, listActiveGatewaysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gateway{}
	for rows.Next() {
		var i Gateway
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.Version,
			&i.DeploymentType,
			&i.PublicUrl,
			&i.QuicPort,
			&i.GrpcPort,
			&i.HttpsPort,
			&i.IpAddress,
			&i.LastHeartbeat,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.LogToCp,
			&i.Uptime,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsByGateway = `-- name: ListConnectorsByGateway :many
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at FROM connectors
WHERE gateway_id = $1
  AND is_active = true
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByGateway, gatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GatewayID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeen,
			&i.Status,
			&i.CreatedAt,
			&i.IsActive,
			&i.OpenSock,
			&i.ActiveStreams,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsByOrg = `-- name: ListConnectorsByOrg :many
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at FROM connectors
WHERE org_id     = $1
ORDER BY created_at ASC
`

func (q *Queries) ListConnectorsByOrg(ctx context.Context, orgID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GatewayID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeen,
			&i.Status,
			&i.CreatedAt,
			&i.IsActive,
			&i.OpenSock,
			&i.ActiveStreams,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsWithGatewayNameByOrg = `-- name: ListConnectorsWithGatewayNameByOrg :many
SELECT c.id, c.org_id, c.gateway_id, c.name, c.token_hash, c.last_seen, c.status, c.created_at, c.is_active, c.open_sock, c.active_streams, c.enrolled_at, c.revoked_at, g.name AS gateway_name
FROM connectors c
JOIN gateways g ON c.gateway_id = g.id
WHERE c.org_id = $1
ORDER BY c.created_at ASC
`

type ListConnectorsWithGatewayNameByOrgRow struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	GatewayID     uuid.UUID          `json:"gateway_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	IsActive      bool               `json:"is_active"`
	OpenSock      bool               `json:"open_sock"`
	ActiveStreams int32              `json:"active_streams"`
	EnrolledAt    pgtype.Timestamptz `json:"enrolled_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	GatewayName   string             `json:"gateway_name"`
}

func (q *Queries) ListConnectorsWithGatewayNameByOrg(ctx context.Context, orgID uuid.UUID) ([]ListConnectorsWithGatewayNameByOrgRow, error) {
	rows, err := q.db.Query(ctx, listConnectorsWithGatewayNameByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectorsWithGatewayNameByOrgRow{}
	for rows.Next() {
		var i ListConnectorsWithGatewayNameByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GatewayID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeen,
			&i.Status,
			&i.CreatedAt,
			&i.IsActive,
			&i.OpenSock,
			&i.ActiveStreams,
			&i.EnrolledAt,
			&i.RevokedAt,
			&i.GatewayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewaysByOrg = `-- name: ListGatewaysByOrg :many
SELECT id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at FROM gateways
WHERE org_id     = $1
ORDER BY created_at ASC
`

func (q *Queries) ListGatewaysByOrg(ctx context.Context, orgID uuid.UUID) ([]Gateway, error) {
	rows, err := q.db.Query(ctx, listGatewaysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gateway{}
	for rows.Next() {
		var i Gateway
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.Version,
			&i.DeploymentType,
			&i.PublicUrl,
			&i.QuicPort,
			&i.GrpcPort,
			&i.HttpsPort,
			&i.IpAddress,
			&i.LastHeartbeat,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.LogToCp,
			&i.Uptime,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reCreateConnector = `-- name: ReCreateConnector :one
UPDATE connectors 
SET created_at = NOW(), 
    status = 'pending',
    last_seen = NULL,
    revoked_at = NULL,
    is_active = true,
    active_streams = 0,
    open_sock = $5,
    token_hash = $2,
    name = $3,
    gateway_id = $4
WHERE id = $1
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at
`

type ReCreateConnectorParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
	Name      string    `json:"name"`
	GatewayID uuid.UUID `json:"gateway_id"`
	OpenSock  bool      `json:"open_sock"`
}

func (q *Queries) ReCreateConnector(ctx context.Context, arg ReCreateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, reCreateConnector,
		arg.ID,
		arg.TokenHash,
		arg.Name,
		arg.GatewayID,
		arg.OpenSock,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const reCreateGateway = `-- name: ReCreateGateway :one
UPDATE gateways 
SET created_at = NOW(), 
    status = 'pending',
    last_heartbeat = NULL,
    revoked_at = NULL,
    version = NULL,
    http_port = NULL,
    quic_port = NULL,
    grpc_port = NULL,
    is_active = true,
    log_to_cp = $6,
    ip_address = $5,
    public_url = $4,
    token_hash = $2,
    name = $3
WHERE id = $1
RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
`

type ReCreateGatewayParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
	Name      string    `json:"name"`
	PublicUrl string    `json:"public_url"`
	IpAddress string    `json:"ip_address"`
	LogToCp   bool      `json:"log_to_cp"`
}

func (q *Queries) ReCreateGateway(ctx context.Context, arg ReCreateGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, reCreateGateway,
		arg.ID,
		arg.TokenHash,
		arg.Name,
		arg.PublicUrl,
		arg.IpAddress,
		arg.LogToCp,
	)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeConnector = `-- name: RevokeConnector :one
UPDATE connectors
SET revoked_at = now(),
    status     = 'disconnected',
    is_active = false,
    active_streams = 0
WHERE id         = $1
  AND gateway_id     = $2
  AND is_active = true
  AND revoked_at IS NULL
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at
`

type RevokeConnectorParams struct {
	ID        uuid.UUID `json:"id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) RevokeConnector(ctx context.Context, arg RevokeConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, revokeConnector, arg.ID, arg.GatewayID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeConnectorsByGateway = `-- name: RevokeConnectorsByGateway :exec
UPDATE connectors
SET revoked_at = now(),
    status     = 'disconnected',
    active_streams = 0,
    is_active = false
WHERE gateway_id = $1
  AND revoked_at IS NULL
`

// Called when a gateway is revoked — cascade revoke all its connectors.
func (q *Queries) RevokeConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeConnectorsByGateway, gatewayID)
	return err
}

const revokeGateway = `-- name: RevokeGateway :one
UPDATE gateways
SET revoked_at = now(),
    status     = 'offline',
    is_active = false
WHERE id         = $1
  AND org_id     = $2
  AND is_active = true
  AND revoked_at IS NULL
RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
`

type RevokeGatewayParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Immediately disconnects gateway. Token becomes invalid.
func (q *Queries) RevokeGateway(ctx context.Context, arg RevokeGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, revokeGateway, arg.ID, arg.OrgID)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateConnectorStatus = `-- name: UpdateConnectorStatus :one
UPDATE connectors
SET last_seen = now(),
    active_streams = $3,
    status    = $2
WHERE id      = $1
  AND is_active = true
  AND revoked_at IS NULL
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, is_active, open_sock, active_streams, enrolled_at, revoked_at
`

type UpdateConnectorStatusParams struct {
	ID            uuid.UUID `json:"id"`
	Status        string    `json:"status"`
	ActiveStreams int32     `json:"active_streams"`
}

func (q *Queries) UpdateConnectorStatus(ctx context.Context, arg UpdateConnectorStatusParams) (Connector, error) {
	row := q.db.QueryRow(ctx, updateConnectorStatus, arg.ID, arg.Status, arg.ActiveStreams)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.IsActive,
		&i.OpenSock,
		&i.ActiveStreams,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateGatewayHeartbeat = `-- name: UpdateGatewayHeartbeat :one
UPDATE gateways
SET last_heartbeat = now()
WHERE id           = $1
  AND is_active = true
  AND revoked_at   IS NULL
RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
`

// Called every 30s by Gateway. Updates last_heartbeat and version.
func (q *Queries) UpdateGatewayHeartbeat(ctx context.Context, id uuid.UUID) (Gateway, error) {
	row := q.db.QueryRow(ctx, updateGatewayHeartbeat, id)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateGatewayInfo = `-- name: UpdateGatewayInfo :one
UPDATE gateways
SET version = $5,
    quic_port = $4,
    https_port = $3,
    grpc_port = $2,
    uptime = $6
WHERE id = $1
  AND is_active = true
  AND revoked_at IS NULL
RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
`

type UpdateGatewayInfoParams struct {
	ID        uuid.UUID   `json:"id"`
	GrpcPort  pgtype.Text `json:"grpc_port"`
	HttpsPort pgtype.Text `json:"https_port"`
	QuicPort  pgtype.Text `json:"quic_port"`
	Version   pgtype.Text `json:"version"`
	Uptime    int64       `json:"uptime"`
}

func (q *Queries) UpdateGatewayInfo(ctx context.Context, arg UpdateGatewayInfoParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, updateGatewayInfo,
		arg.ID,
		arg.GrpcPort,
		arg.HttpsPort,
		arg.QuicPort,
		arg.Version,
		arg.Uptime,
	)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateGatewayStatus = `-- name: UpdateGatewayStatus :one
UPDATE gateways
SET status = $2
WHERE id = $1
  AND is_active = true
  AND revoked_at IS NULL
RETURNING id, org_id, name, token_hash, version, deployment_type, public_url, quic_port, grpc_port, https_port, ip_address, last_heartbeat, status, is_active, created_at, log_to_cp, uptime, enrolled_at, revoked_at
`

type UpdateGatewayStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateGatewayStatus(ctx context.Context, arg UpdateGatewayStatusParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, updateGatewayStatus, arg.ID, arg.Status)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.DeploymentType,
		&i.PublicUrl,
		&i.QuicPort,
		&i.GrpcPort,
		&i.HttpsPort,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.LogToCp,
		&i.Uptime,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}
