// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateways_connectors.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConnector = `-- name: CreateConnector :one

INSERT INTO connectors (org_id, gateway_id, name, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at
`

type CreateConnectorParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
}

// =================================================================
// CONNECTORS
// token_hash: SHA-256 of connector enrollment token.
// =================================================================
func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, createConnector,
		arg.OrgID,
		arg.GatewayID,
		arg.Name,
		arg.TokenHash,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const createGateway = `-- name: CreateGateway :one

INSERT INTO gateways (org_id, name, token_hash)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at
`

type CreateGatewayParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
}

// =================================================================
// GATEWAYS
// token_hash: SHA-256 of enrollment token. Never plaintext.
// =================================================================
func (q *Queries) CreateGateway(ctx context.Context, arg CreateGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, createGateway, arg.OrgID, arg.Name, arg.TokenHash)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const enrollGateway = `-- name: EnrollGateway :one
UPDATE gateways 
SET enrolled_at = NOW(), 
    status = 'healthy',
    last_heartbeat = NOW()
WHERE token_hash = $1
AND revoked_at IS NULL
RETURNING id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at
`

func (q *Queries) EnrollGateway(ctx context.Context, tokenHash string) (Gateway, error) {
	row := q.db.QueryRow(ctx, enrollGateway, tokenHash)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConnectorByID = `-- name: GetConnectorByID :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at FROM connectors
WHERE id         = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByID, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConnectorByIDAndOrg = `-- name: GetConnectorByIDAndOrg :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at FROM connectors
WHERE id         = $1
  AND org_id     = $2
  AND revoked_at IS NULL
`

type GetConnectorByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetConnectorByIDAndOrg(ctx context.Context, arg GetConnectorByIDAndOrgParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByIDAndOrg, arg.ID, arg.OrgID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConnectorByTokenHash = `-- name: GetConnectorByTokenHash :one
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at FROM connectors
WHERE token_hash = $1
  AND revoked_at IS NULL
`

// Called on connector → gateway auth.
func (q *Queries) GetConnectorByTokenHash(ctx context.Context, tokenHash string) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByTokenHash, tokenHash)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGatewayByID = `-- name: GetGatewayByID :one
SELECT id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at FROM gateways
WHERE id         = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetGatewayByID(ctx context.Context, id uuid.UUID) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByID, id)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGatewayByIDAndOrg = `-- name: GetGatewayByIDAndOrg :one
SELECT id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at FROM gateways
WHERE id         = $1
  AND org_id     = $2
  AND revoked_at IS NULL
`

type GetGatewayByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetGatewayByIDAndOrg(ctx context.Context, arg GetGatewayByIDAndOrgParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByIDAndOrg, arg.ID, arg.OrgID)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGatewayByTokenHash = `-- name: GetGatewayByTokenHash :one
SELECT id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at FROM gateways
WHERE token_hash = $1
  AND status = 'pending'
  AND revoked_at IS NULL
`

// Called on every Gateway → CP request (heartbeat, policy sync).
// Keep this fast — it is on the service path.
func (q *Queries) GetGatewayByTokenHash(ctx context.Context, tokenHash string) (Gateway, error) {
	row := q.db.QueryRow(ctx, getGatewayByTokenHash, tokenHash)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const listConnectorsByGateway = `-- name: ListConnectorsByGateway :many
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at FROM connectors
WHERE gateway_id = $1
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByGateway, gatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GatewayID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeen,
			&i.Status,
			&i.CreatedAt,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsByOrg = `-- name: ListConnectorsByOrg :many
SELECT id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at FROM connectors
WHERE org_id     = $1
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListConnectorsByOrg(ctx context.Context, orgID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GatewayID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeen,
			&i.Status,
			&i.CreatedAt,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewaysByOrg = `-- name: ListGatewaysByOrg :many
SELECT id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at FROM gateways
WHERE org_id     = $1
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListGatewaysByOrg(ctx context.Context, orgID uuid.UUID) ([]Gateway, error) {
	rows, err := q.db.Query(ctx, listGatewaysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gateway{}
	for rows.Next() {
		var i Gateway
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.Version,
			&i.LastHeartbeat,
			&i.Status,
			&i.CreatedAt,
			&i.EnrolledAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reCreateGateway = `-- name: ReCreateGateway :one
UPDATE gateways 
SET created_at = NOW(), 
    status = 'pending',
    last_heartbeat = NULL,
    version = NULL,
    token_hash = $2,
    name = $3
WHERE id = $1
RETURNING id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at
`

type ReCreateGatewayParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
	Name      string    `json:"name"`
}

func (q *Queries) ReCreateGateway(ctx context.Context, arg ReCreateGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, reCreateGateway, arg.ID, arg.TokenHash, arg.Name)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeConnector = `-- name: RevokeConnector :one
UPDATE connectors
SET revoked_at = now(),
    status     = 'disconnected'
WHERE id         = $1
  AND org_id     = $2
  AND revoked_at IS NULL
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at
`

type RevokeConnectorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) RevokeConnector(ctx context.Context, arg RevokeConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, revokeConnector, arg.ID, arg.OrgID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeConnectorsByGateway = `-- name: RevokeConnectorsByGateway :exec
UPDATE connectors
SET revoked_at = now(),
    status     = 'disconnected'
WHERE gateway_id = $1
  AND revoked_at IS NULL
`

// Called when a gateway is revoked — cascade revoke all its connectors.
func (q *Queries) RevokeConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeConnectorsByGateway, gatewayID)
	return err
}

const revokeGateway = `-- name: RevokeGateway :one
UPDATE gateways
SET revoked_at = now(),
    status     = 'offline'
WHERE id         = $1
  AND org_id     = $2
  AND revoked_at IS NULL
RETURNING id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at
`

type RevokeGatewayParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Immediately disconnects gateway. Token becomes invalid.
func (q *Queries) RevokeGateway(ctx context.Context, arg RevokeGatewayParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, revokeGateway, arg.ID, arg.OrgID)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateConnectorLastSeen = `-- name: UpdateConnectorLastSeen :one
UPDATE connectors
SET last_seen = now(),
    status    = $2
WHERE id      = $1
RETURNING id, org_id, gateway_id, name, token_hash, last_seen, status, created_at, enrolled_at, revoked_at
`

type UpdateConnectorLastSeenParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateConnectorLastSeen(ctx context.Context, arg UpdateConnectorLastSeenParams) (Connector, error) {
	row := q.db.QueryRow(ctx, updateConnectorLastSeen, arg.ID, arg.Status)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GatewayID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeen,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateGatewayHeartbeat = `-- name: UpdateGatewayHeartbeat :one
UPDATE gateways
SET last_heartbeat = now(),
    version        = $2,
    status         = $3
WHERE id           = $1
  AND revoked_at   IS NULL
RETURNING id, org_id, name, token_hash, version, last_heartbeat, status, created_at, enrolled_at, revoked_at
`

type UpdateGatewayHeartbeatParams struct {
	ID      uuid.UUID   `json:"id"`
	Version pgtype.Text `json:"version"`
	Status  string      `json:"status"`
}

// Called every 30s by Gateway. Updates last_heartbeat and version.
func (q *Queries) UpdateGatewayHeartbeat(ctx context.Context, arg UpdateGatewayHeartbeatParams) (Gateway, error) {
	row := q.db.QueryRow(ctx, updateGatewayHeartbeat, arg.ID, arg.Version, arg.Status)
	var i Gateway
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.EnrolledAt,
		&i.RevokedAt,
	)
	return i, err
}
