// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idp_configs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createIDPConfig = `-- name: CreateIDPConfig :one

INSERT INTO idp_configs (org_id, name, provider_type, client_id, client_secret, issuer_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at
`

type CreateIDPConfigParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	Name         string    `json:"name"`
	ProviderType string    `json:"provider_type"`
	ClientID     string    `json:"client_id"`
	ClientSecret string    `json:"client_secret"`
	IssuerUrl    string    `json:"issuer_url"`
}

// =================================================================
// IDP CONFIGS
// client_secret must be AES-256-GCM encrypted before insert.
// Never store or return plaintext secrets.
// =================================================================
func (q *Queries) CreateIDPConfig(ctx context.Context, arg CreateIDPConfigParams) (IdpConfig, error) {
	row := q.db.QueryRow(ctx, createIDPConfig,
		arg.OrgID,
		arg.Name,
		arg.ProviderType,
		arg.ClientID,
		arg.ClientSecret,
		arg.IssuerUrl,
	)
	var i IdpConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderType,
		&i.ClientID,
		&i.ClientSecret,
		&i.IssuerUrl,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIDPConfig = `-- name: DeleteIDPConfig :one
UPDATE idp_configs
SET deleted_at = now()
WHERE id        = $1
  AND org_id    = $2
  AND deleted_at IS NULL
RETURNING id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at
`

type DeleteIDPConfigParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Soft delete. Cannot delete if it is the only verified active IdP
// — enforce this check in the service layer before calling.
func (q *Queries) DeleteIDPConfig(ctx context.Context, arg DeleteIDPConfigParams) (IdpConfig, error) {
	row := q.db.QueryRow(ctx, deleteIDPConfig, arg.ID, arg.OrgID)
	var i IdpConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderType,
		&i.ClientID,
		&i.ClientSecret,
		&i.IssuerUrl,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIDPConfigByID = `-- name: GetIDPConfigByID :one
SELECT id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at FROM idp_configs
WHERE id         = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetIDPConfigByID(ctx context.Context, id uuid.UUID) (IdpConfig, error) {
	row := q.db.QueryRow(ctx, getIDPConfigByID, id)
	var i IdpConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderType,
		&i.ClientID,
		&i.ClientSecret,
		&i.IssuerUrl,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIDPConfigByIDAndOrg = `-- name: GetIDPConfigByIDAndOrg :one
SELECT id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at FROM idp_configs
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
`

type GetIDPConfigByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Always scope to org — never allow cross-org access.
func (q *Queries) GetIDPConfigByIDAndOrg(ctx context.Context, arg GetIDPConfigByIDAndOrgParams) (IdpConfig, error) {
	row := q.db.QueryRow(ctx, getIDPConfigByIDAndOrg, arg.ID, arg.OrgID)
	var i IdpConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderType,
		&i.ClientID,
		&i.ClientSecret,
		&i.IssuerUrl,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveIDPConfigsByOrg = `-- name: ListActiveIDPConfigsByOrg :many
SELECT id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at FROM idp_configs
WHERE org_id     = $1
  AND is_active  = true
  AND is_verified = true
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

// Used by Gateway during OIDC flow to find valid providers.
func (q *Queries) ListActiveIDPConfigsByOrg(ctx context.Context, orgID uuid.UUID) ([]IdpConfig, error) {
	rows, err := q.db.Query(ctx, listActiveIDPConfigsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdpConfig{}
	for rows.Next() {
		var i IdpConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ProviderType,
			&i.ClientID,
			&i.ClientSecret,
			&i.IssuerUrl,
			&i.IsActive,
			&i.IsVerified,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIDPConfigsByOrg = `-- name: ListIDPConfigsByOrg :many
SELECT id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at FROM idp_configs
WHERE org_id     = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListIDPConfigsByOrg(ctx context.Context, orgID uuid.UUID) ([]IdpConfig, error) {
	rows, err := q.db.Query(ctx, listIDPConfigsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdpConfig{}
	for rows.Next() {
		var i IdpConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ProviderType,
			&i.ClientID,
			&i.ClientSecret,
			&i.IssuerUrl,
			&i.IsActive,
			&i.IsVerified,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIDPConfigVerified = `-- name: MarkIDPConfigVerified :one
UPDATE idp_configs
SET is_verified = true
WHERE id        = $1
  AND org_id    = $2
  AND deleted_at IS NULL
RETURNING id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at
`

type MarkIDPConfigVerifiedParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Called after owner completes SSO binding confirmation flow.
func (q *Queries) MarkIDPConfigVerified(ctx context.Context, arg MarkIDPConfigVerifiedParams) (IdpConfig, error) {
	row := q.db.QueryRow(ctx, markIDPConfigVerified, arg.ID, arg.OrgID)
	var i IdpConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderType,
		&i.ClientID,
		&i.ClientSecret,
		&i.IssuerUrl,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIDPConfig = `-- name: UpdateIDPConfig :one
UPDATE idp_configs
SET name          = $3,
    client_id     = $4,
    client_secret = $5,
    issuer_url    = $6,
    is_active     = $7
WHERE id          = $1
  AND org_id      = $2
  AND deleted_at  IS NULL
RETURNING id, org_id, name, provider_type, client_id, client_secret, issuer_url, is_active, is_verified, created_at, deleted_at
`

type UpdateIDPConfigParams struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	Name         string    `json:"name"`
	ClientID     string    `json:"client_id"`
	ClientSecret string    `json:"client_secret"`
	IssuerUrl    string    `json:"issuer_url"`
	IsActive     bool      `json:"is_active"`
}

// Updating secrets rotates the encrypted value.
func (q *Queries) UpdateIDPConfig(ctx context.Context, arg UpdateIDPConfigParams) (IdpConfig, error) {
	row := q.db.QueryRow(ctx, updateIDPConfig,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ClientID,
		arg.ClientSecret,
		arg.IssuerUrl,
		arg.IsActive,
	)
	var i IdpConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderType,
		&i.ClientID,
		&i.ClientSecret,
		&i.IssuerUrl,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
