// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateAccessLogsParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	IdpConfigID pgtype.UUID `json:"idp_config_id"`
	UserEmail   pgtype.Text `json:"user_email"`
	Method      pgtype.Text `json:"method"`
	Path        pgtype.Text `json:"path"`
	Status      pgtype.Int4 `json:"status"`
	LatencyMs   pgtype.Int4 `json:"latency_ms"`
	Ip          pgtype.Text `json:"ip"`
	Result      string      `json:"result"`
	DenyReason  pgtype.Text `json:"deny_reason"`
}

const countAccessLogsByResult = `-- name: CountAccessLogsByResult :one
SELECT
    COUNT(*) FILTER (WHERE result = 'allowed') AS allowed_count,
    COUNT(*) FILTER (WHERE result = 'denied')  AS denied_count
FROM access_logs
WHERE org_id     = $1
  AND created_at >= $2
  AND created_at <= $3
`

type CountAccessLogsByResultParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type CountAccessLogsByResultRow struct {
	AllowedCount int64 `json:"allowed_count"`
	DeniedCount  int64 `json:"denied_count"`
}

// Dashboard summary counts.
func (q *Queries) CountAccessLogsByResult(ctx context.Context, arg CountAccessLogsByResultParams) (CountAccessLogsByResultRow, error) {
	row := q.db.QueryRow(ctx, countAccessLogsByResult, arg.OrgID, arg.CreatedAt, arg.CreatedAt_2)
	var i CountAccessLogsByResultRow
	err := row.Scan(&i.AllowedCount, &i.DeniedCount)
	return i, err
}

const countAppTrafficToday = `-- name: CountAppTrafficToday :one
SELECT COUNT(*)::bigint AS traffic_count FROM access_logs
WHERE app_id = $1
  AND created_at >= CURRENT_DATE
`

func (q *Queries) CountAppTrafficToday(ctx context.Context, appID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAppTrafficToday, appID)
	var traffic_count int64
	err := row.Scan(&traffic_count)
	return traffic_count, err
}

const createAccessLog = `-- name: CreateAccessLog :one

INSERT INTO access_logs (
    org_id, app_id, idp_config_id, user_email,
    method, path, status, latency_ms,
    ip, result, deny_reason
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at
`

type CreateAccessLogParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	IdpConfigID pgtype.UUID `json:"idp_config_id"`
	UserEmail   pgtype.Text `json:"user_email"`
	Method      pgtype.Text `json:"method"`
	Path        pgtype.Text `json:"path"`
	Status      pgtype.Int4 `json:"status"`
	LatencyMs   pgtype.Int4 `json:"latency_ms"`
	Ip          pgtype.Text `json:"ip"`
	Result      string      `json:"result"`
	DenyReason  pgtype.Text `json:"deny_reason"`
}

// =================================================================
// ACCESS LOGS
// Written async by Gateway in batches. CP never in traffic path.
// =================================================================
func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (AccessLog, error) {
	row := q.db.QueryRow(ctx, createAccessLog,
		arg.OrgID,
		arg.AppID,
		arg.IdpConfigID,
		arg.UserEmail,
		arg.Method,
		arg.Path,
		arg.Status,
		arg.LatencyMs,
		arg.Ip,
		arg.Result,
		arg.DenyReason,
	)
	var i AccessLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.IdpConfigID,
		&i.UserEmail,
		&i.Method,
		&i.Path,
		&i.Status,
		&i.LatencyMs,
		&i.Ip,
		&i.Result,
		&i.DenyReason,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (org_id, actor_id, action, target_type, target_id, details, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, actor_id, action, target_type, target_id, details, ip, created_at
`

type CreateAuditLogParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Details    []byte      `json:"details"`
	Ip         pgtype.Text `json:"ip"`
}

// =================================================================
// AUDIT LOGS
// Append-only. Never update or delete.
// =================================================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.Ip,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Details,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessLogsByApp = `-- name: ListAccessLogsByApp :many
SELECT id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at FROM access_logs
WHERE app_id     = $1
  AND org_id     = $2
  AND created_at >= $3
  AND created_at <= $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAccessLogsByAppParams struct {
	AppID       pgtype.UUID `json:"app_id"`
	OrgID       uuid.UUID   `json:"org_id"`
	CreatedAt   time.Time   `json:"created_at"`
	CreatedAt_2 time.Time   `json:"created_at_2"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListAccessLogsByApp(ctx context.Context, arg ListAccessLogsByAppParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, listAccessLogsByApp,
		arg.AppID,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.IdpConfigID,
			&i.UserEmail,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Ip,
			&i.Result,
			&i.DenyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessLogsByOrg = `-- name: ListAccessLogsByOrg :many
SELECT id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at FROM access_logs
WHERE org_id     = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAccessLogsByOrgParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListAccessLogsByOrg(ctx context.Context, arg ListAccessLogsByOrgParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, listAccessLogsByOrg,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.IdpConfigID,
			&i.UserEmail,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Ip,
			&i.Result,
			&i.DenyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, org_id, actor_id, action, target_type, target_id, details, ip, created_at FROM audit_logs
WHERE org_id     = $1
  AND actor_id   = $2
  AND created_at >= $3
  AND created_at <= $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsByActorParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	CreatedAt   time.Time   `json:"created_at"`
	CreatedAt_2 time.Time   `json:"created_at_2"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor,
		arg.OrgID,
		arg.ActorID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, org_id, actor_id, action, target_type, target_id, details, ip, created_at FROM audit_logs
WHERE org_id     = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsByOrgParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTarget = `-- name: ListAuditLogsByTarget :many
SELECT id, org_id, actor_id, action, target_type, target_id, details, ip, created_at FROM audit_logs
WHERE org_id      = $1
  AND target_type = $2
  AND target_id   = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsByTargetParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTarget,
		arg.OrgID,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeniedAccessLogs = `-- name: ListDeniedAccessLogs :many
SELECT id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at FROM access_logs
WHERE org_id     = $1
  AND result     = 'denied'
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListDeniedAccessLogsParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

// Dashboard denied requests view.
func (q *Queries) ListDeniedAccessLogs(ctx context.Context, arg ListDeniedAccessLogsParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, listDeniedAccessLogs,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.IdpConfigID,
			&i.UserEmail,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Ip,
			&i.Result,
			&i.DenyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldAccessLogs = `-- name: PurgeOldAccessLogs :exec
DELETE FROM access_logs
WHERE created_at < now() - ($1 || ' days')::interval
`

// Retention policy. Default 90 days. Run via background job.
func (q *Queries) PurgeOldAccessLogs(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, purgeOldAccessLogs, dollar_1)
	return err
}
