// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessLog struct {
	ID         uuid.UUID   `json:"id"`
	OrgID      uuid.UUID   `json:"org_id"`
	GatewayID  pgtype.UUID `json:"gateway_id"`
	AppID      pgtype.UUID `json:"app_id"`
	PolicyID   pgtype.UUID `json:"policy_id"`
	UserID     pgtype.Text `json:"user_id"`
	UserEmail  pgtype.Text `json:"user_email"`
	Method     pgtype.Text `json:"method"`
	Path       pgtype.Text `json:"path"`
	Status     pgtype.Int4 `json:"status"`
	LatencyMs  pgtype.Int4 `json:"latency_ms"`
	Action     pgtype.Text `json:"action"`
	Ip         pgtype.Text `json:"ip"`
	Result     string      `json:"result"`
	DenyReason pgtype.Text `json:"deny_reason"`
	BytesIn    int64       `json:"bytes_in"`
	BytesOut   int64       `json:"bytes_out"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Admin struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IdpSubject   pgtype.Text        `json:"idp_subject"`
	IdpConfigID  pgtype.UUID        `json:"idp_config_id"`
	SsoBound     bool               `json:"sso_bound"`
	SsoOnly      bool               `json:"sso_only"`
	OtpSecret    pgtype.Text        `json:"otp_secret"`
	OtpEnabled   bool               `json:"otp_enabled"`
	IsActive     bool               `json:"is_active"`
	Role         string             `json:"role"`
	InvitedBy    pgtype.UUID        `json:"invited_by"`
	CreatedAt    time.Time          `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type AdminSession struct {
	ID           uuid.UUID          `json:"id"`
	AdminID      uuid.UUID          `json:"admin_id"`
	OrgID        uuid.UUID          `json:"org_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    time.Time          `json:"expires_at"`
	CreatedAt    time.Time          `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type AdminSetupToken struct {
	ID        uuid.UUID          `json:"id"`
	AdminID   uuid.UUID          `json:"admin_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type App struct {
	ID                    uuid.UUID          `json:"id"`
	OrgID                 uuid.UUID          `json:"org_id"`
	ConnectorID           pgtype.UUID        `json:"connector_id"`
	Name                  string             `json:"name"`
	Subdomain             string             `json:"subdomain"`
	Upstream              string             `json:"upstream"`
	Protocol              string             `json:"protocol"`
	IsPublic              bool               `json:"is_public"`
	EnableSecurityHeaders bool               `json:"enable_security_headers"`
	CheckHealth           bool               `json:"check_health"`
	CheckInterval         int32              `json:"check_interval"`
	HealthEndpoint        pgtype.Text        `json:"health_endpoint"`
	HealthStatus          string             `json:"health_status"`
	LastSeen              pgtype.Timestamptz `json:"last_seen"`
	SockPass              string             `json:"sock_pass"`
	CreatedAt             time.Time          `json:"created_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type AppIdpMapping struct {
	ID         uuid.UUID `json:"id"`
	AppID      uuid.UUID `json:"app_id"`
	IdpID      uuid.UUID `json:"idp_id"`
	IsRequired bool      `json:"is_required"`
	CreatedAt  time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	OrgID      uuid.UUID   `json:"org_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Details    []byte      `json:"details"`
	Ip         pgtype.Text `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type CaCertificate struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	CertPem      string             `json:"cert_pem"`
	SerialNumber string             `json:"serial_number"`
	Subject      string             `json:"subject"`
	IssuedAt     time.Time          `json:"issued_at"`
	ExpiresAt    time.Time          `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type ComponentCertificate struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	ComponentType string             `json:"component_type"`
	ComponentID   pgtype.UUID        `json:"component_id"`
	CaID          uuid.UUID          `json:"ca_id"`
	CertPem       string             `json:"cert_pem"`
	SerialNumber  string             `json:"serial_number"`
	Subject       string             `json:"subject"`
	San           []string           `json:"san"`
	IssuedAt      time.Time          `json:"issued_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason  pgtype.Text        `json:"revoke_reason"`
	RotationOf    pgtype.UUID        `json:"rotation_of"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Connector struct {
	ID                 uuid.UUID          `json:"id"`
	OrgID              uuid.UUID          `json:"org_id"`
	GatewayID          uuid.UUID          `json:"gateway_id"`
	SecondaryGatewayID pgtype.UUID        `json:"secondary_gateway_id"`
	Name               string             `json:"name"`
	TokenHash          string             `json:"token_hash"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	Status             string             `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	IsActive           bool               `json:"is_active"`
	OpenSock           bool               `json:"open_sock"`
	ActiveStreams      int32              `json:"active_streams"`
	EnrolledAt         pgtype.Timestamptz `json:"enrolled_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
}

type CrlEntry struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	CertID       uuid.UUID `json:"cert_id"`
	SerialNumber string    `json:"serial_number"`
	RevokedAt    time.Time `json:"revoked_at"`
	Reason       string    `json:"reason"`
}

type Gateway struct {
	ID             uuid.UUID          `json:"id"`
	OrgID          uuid.UUID          `json:"org_id"`
	Name           string             `json:"name"`
	TokenHash      string             `json:"token_hash"`
	Version        pgtype.Text        `json:"version"`
	DeploymentType string             `json:"deployment_type"`
	PublicUrl      string             `json:"public_url"`
	QuicPort       pgtype.Text        `json:"quic_port"`
	GrpcPort       pgtype.Text        `json:"grpc_port"`
	HttpsPort      pgtype.Text        `json:"https_port"`
	IpAddress      string             `json:"ip_address"`
	LastHeartbeat  pgtype.Timestamptz `json:"last_heartbeat"`
	Status         string             `json:"status"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      time.Time          `json:"created_at"`
	LogToCp        bool               `json:"log_to_cp"`
	Uptime         int64              `json:"uptime"`
	EnrolledAt     pgtype.Timestamptz `json:"enrolled_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type GatewayEvent struct {
	GatewayID    uuid.UUID       `json:"gateway_id"`
	Seq          int64           `json:"seq"`
	EventID      uuid.UUID       `json:"event_id"`
	Command      string          `json:"command"`
	DeliveryMode string          `json:"delivery_mode"`
	Payload      json.RawMessage `json:"payload"`
	CreatedAt    time.Time       `json:"created_at"`
}

type GatewayEventSequence struct {
	GatewayID uuid.UUID `json:"gateway_id"`
	NextSeq   int64     `json:"next_seq"`
}

type GatewayEventsAck struct {
	GatewayID    uuid.UUID `json:"gateway_id"`
	LastAckedSeq int64     `json:"last_acked_seq"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type IdpConfig struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Name         string             `json:"name"`
	ProviderType string             `json:"provider_type"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	IssuerUrl    string             `json:"issuer_url"`
	Scopes       []string           `json:"scopes"`
	EmailClaim   string             `json:"email_claim"`
	NameClaim    string             `json:"name_claim"`
	GroupClaim   string             `json:"group_claim"`
	ExtraConfig  json.RawMessage    `json:"extra_config"`
	IsActive     bool               `json:"is_active"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    time.Time          `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Org struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	Slug                    string             `json:"slug"`
	CustomDomain            pgtype.Text        `json:"custom_domain"`
	DomainVerified          bool               `json:"domain_verified"`
	DomainVerificationToken pgtype.Text        `json:"domain_verification_token"`
	CreatedAt               time.Time          `json:"created_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	AdminID   uuid.UUID          `json:"admin_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Policy struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       uuid.UUID   `json:"org_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Effect      string      `json:"effect"`
	Priority    pgtype.Int4 `json:"priority"`
	Enabled     bool        `json:"enabled"`
	Version     int64       `json:"version"`
	Sequence    int64       `json:"sequence"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type PolicyCondition struct {
	PolicyID      uuid.UUID       `json:"policy_id"`
	ConditionTree json.RawMessage `json:"condition_tree"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type PolicyMutation struct {
	ID              uuid.UUID       `json:"id"`
	Sequence        int64           `json:"sequence"`
	OrgID           uuid.UUID       `json:"org_id"`
	PolicyID        uuid.UUID       `json:"policy_id"`
	Op              string          `json:"op"`
	RuleSnapshot    json.RawMessage `json:"rule_snapshot"`
	OldRuleSnapshot []byte          `json:"old_rule_snapshot"`
	Version         int64           `json:"version"`
	Signature       []byte          `json:"signature"`
	RecordTimestamp int64           `json:"record_timestamp"`
	MutatedBy       pgtype.UUID     `json:"mutated_by"`
	MutatedAt       time.Time       `json:"mutated_at"`
	IpAddress       *netip.Addr     `json:"ip_address"`
	UserAgent       pgtype.Text     `json:"user_agent"`
}

type PolicyResource struct {
	PolicyID      uuid.UUID `json:"policy_id"`
	ResourceType  string    `json:"resource_type"`
	ResourceValue string    `json:"resource_value"`
}

type PolicySubject struct {
	PolicyID     uuid.UUID `json:"policy_id"`
	SubjectType  string    `json:"subject_type"`
	SubjectValue string    `json:"subject_value"`
}

type Schedule struct {
	ID        uuid.UUID       `json:"id"`
	OrgID     uuid.UUID       `json:"org_id"`
	Name      string          `json:"name"`
	Timezone  string          `json:"timezone"`
	Rules     json.RawMessage `json:"rules"`
	CreatedBy uuid.UUID       `json:"created_by"`
	CreatedAt time.Time       `json:"created_at"`
}

type UserSession struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	UserID    uuid.UUID          `json:"user_id"`
	UserEmail string             `json:"user_email"`
	GatewayID uuid.UUID          `json:"gateway_id"`
	IssuedAt  time.Time          `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}
