// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessLog struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	IdpConfigID pgtype.UUID `json:"idp_config_id"`
	UserEmail   pgtype.Text `json:"user_email"`
	Method      pgtype.Text `json:"method"`
	Path        pgtype.Text `json:"path"`
	Status      pgtype.Int4 `json:"status"`
	LatencyMs   pgtype.Int4 `json:"latency_ms"`
	Ip          pgtype.Text `json:"ip"`
	Result      string      `json:"result"`
	DenyReason  pgtype.Text `json:"deny_reason"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Admin struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IdpSubject   pgtype.Text        `json:"idp_subject"`
	IdpConfigID  pgtype.UUID        `json:"idp_config_id"`
	SsoBound     bool               `json:"sso_bound"`
	SsoOnly      bool               `json:"sso_only"`
	OtpSecret    pgtype.Text        `json:"otp_secret"`
	OtpEnabled   bool               `json:"otp_enabled"`
	IsActive     bool               `json:"is_active"`
	Role         string             `json:"role"`
	InvitedBy    pgtype.UUID        `json:"invited_by"`
	CreatedAt    time.Time          `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type AdminSession struct {
	ID           uuid.UUID          `json:"id"`
	AdminID      uuid.UUID          `json:"admin_id"`
	OrgID        uuid.UUID          `json:"org_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    time.Time          `json:"expires_at"`
	CreatedAt    time.Time          `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type AdminSetupToken struct {
	ID        uuid.UUID          `json:"id"`
	AdminID   uuid.UUID          `json:"admin_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type App struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	ConnectorID pgtype.UUID        `json:"connector_id"`
	Name        string             `json:"name"`
	Subdomain   string             `json:"subdomain"`
	Upstream    string             `json:"upstream"`
	Protocol    string             `json:"protocol"`
	IsPublic    bool               `json:"is_public"`
	CreatedAt   time.Time          `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	OrgID      uuid.UUID   `json:"org_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Details    []byte      `json:"details"`
	Ip         pgtype.Text `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type CaCertificate struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	CertPem      string             `json:"cert_pem"`
	SerialNumber string             `json:"serial_number"`
	Subject      string             `json:"subject"`
	IssuedAt     time.Time          `json:"issued_at"`
	ExpiresAt    time.Time          `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type ComponentCertificate struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	ComponentType string             `json:"component_type"`
	ComponentID   uuid.UUID          `json:"component_id"`
	CaID          uuid.UUID          `json:"ca_id"`
	CertPem       string             `json:"cert_pem"`
	SerialNumber  string             `json:"serial_number"`
	Subject       string             `json:"subject"`
	San           []string           `json:"san"`
	IssuedAt      time.Time          `json:"issued_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason  pgtype.Text        `json:"revoke_reason"`
	RotationOf    pgtype.UUID        `json:"rotation_of"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Connector struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	GatewayID uuid.UUID          `json:"gateway_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	Status    string             `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type CrlEntry struct {
	ID           uuid.UUID `json:"id"`
	CertID       uuid.UUID `json:"cert_id"`
	SerialNumber string    `json:"serial_number"`
	RevokedAt    time.Time `json:"revoked_at"`
	Reason       string    `json:"reason"`
}

type CsrRequest struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	ComponentType string             `json:"component_type"`
	ComponentID   uuid.UUID          `json:"component_id"`
	CsrPem        string             `json:"csr_pem"`
	Status        string             `json:"status"`
	SignedCertID  pgtype.UUID        `json:"signed_cert_id"`
	CreatedAt     time.Time          `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type Gateway struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	Version       pgtype.Text        `json:"version"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type IdpConfig struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Name         string             `json:"name"`
	ProviderType string             `json:"provider_type"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	IssuerUrl    string             `json:"issuer_url"`
	IsActive     bool               `json:"is_active"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    time.Time          `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Org struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	Slug                    string             `json:"slug"`
	CustomDomain            pgtype.Text        `json:"custom_domain"`
	DomainVerified          bool               `json:"domain_verified"`
	DomainVerificationToken pgtype.Text        `json:"domain_verification_token"`
	CreatedAt               time.Time          `json:"created_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	AdminID   uuid.UUID          `json:"admin_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Policy struct {
	ID        uuid.UUID          `json:"id"`
	AppID     uuid.UUID          `json:"app_id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Name      string             `json:"name"`
	Priority  int32              `json:"priority"`
	IsActive  bool               `json:"is_active"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type PolicyRule struct {
	ID        uuid.UUID `json:"id"`
	PolicyID  uuid.UUID `json:"policy_id"`
	Effect    string    `json:"effect"`
	RuleType  string    `json:"rule_type"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type Revocation struct {
	ID        uuid.UUID   `json:"id"`
	OrgID     uuid.UUID   `json:"org_id"`
	Type      string      `json:"type"`
	TargetID  string      `json:"target_id"`
	Reason    pgtype.Text `json:"reason"`
	CreatedAt time.Time   `json:"created_at"`
	ExpiresAt time.Time   `json:"expires_at"`
}
