// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one

INSERT INTO orgs (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at
`

type CreateOrgParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// =================================================================
// ORGS
// =================================================================
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :one
UPDATE orgs
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at
`

// Soft delete only. Hard delete is a manual ops action.
func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, deleteOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgByCustomDomain = `-- name: GetOrgByCustomDomain :one
SELECT id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at FROM orgs
WHERE custom_domain = $1
  AND domain_verified = true
  AND deleted_at IS NULL
`

// Used by Gateway to resolve incoming hostname to org (v2)
func (q *Queries) GetOrgByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByCustomDomain, customDomain)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at FROM orgs
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at FROM orgs
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setOrgCustomDomain = `-- name: SetOrgCustomDomain :one
UPDATE orgs
SET custom_domain               = $2,
    domain_verification_token   = $3,
    domain_verified             = false
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at
`

type SetOrgCustomDomainParams struct {
	ID                      uuid.UUID   `json:"id"`
	CustomDomain            pgtype.Text `json:"custom_domain"`
	DomainVerificationToken pgtype.Text `json:"domain_verification_token"`
}

// Sets custom domain and generates a verification token.
// domain_verified stays false until DNS challenge passes.
func (q *Queries) SetOrgCustomDomain(ctx context.Context, arg SetOrgCustomDomainParams) (Org, error) {
	row := q.db.QueryRow(ctx, setOrgCustomDomain, arg.ID, arg.CustomDomain, arg.DomainVerificationToken)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrgName = `-- name: UpdateOrgName :one
UPDATE orgs
SET name = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at
`

type UpdateOrgNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrgName, arg.ID, arg.Name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyOrgCustomDomain = `-- name: VerifyOrgCustomDomain :one
UPDATE orgs
SET domain_verified = true
WHERE id = $1
  AND domain_verification_token = $2
  AND deleted_at IS NULL
RETURNING id, name, slug, custom_domain, domain_verified, domain_verification_token, created_at, deleted_at
`

type VerifyOrgCustomDomainParams struct {
	ID                      uuid.UUID   `json:"id"`
	DomainVerificationToken pgtype.Text `json:"domain_verification_token"`
}

// Called after CP confirms the DNS TXT record is present.
func (q *Queries) VerifyOrgCustomDomain(ctx context.Context, arg VerifyOrgCustomDomainParams) (Org, error) {
	row := q.db.QueryRow(ctx, verifyOrgCustomDomain, arg.ID, arg.DomainVerificationToken)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.DomainVerificationToken,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
