// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const checkPriorityConflict = `-- name: CheckPriorityConflict :one
SELECT EXISTS (
    SELECT 1 FROM policies
    WHERE app_id   = $1
      AND priority = $2
      AND id      != $3       -- exclude self on update (pass gen_random_uuid() for create)
      AND deleted_at IS NULL
) AS conflict
`

type CheckPriorityConflictParams struct {
	AppID    uuid.UUID `json:"app_id"`
	Priority int32     `json:"priority"`
	ID       uuid.UUID `json:"id"`
}

// Call before CreatePolicy or UpdatePolicy to prevent duplicate priority.
func (q *Queries) CheckPriorityConflict(ctx context.Context, arg CheckPriorityConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPriorityConflict, arg.AppID, arg.Priority, arg.ID)
	var conflict bool
	err := row.Scan(&conflict)
	return conflict, err
}

const createPolicy = `-- name: CreatePolicy :one

INSERT INTO policies (app_id, org_id, name, priority)
VALUES ($1, $2, $3, $4)
RETURNING id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at
`

type CreatePolicyParams struct {
	AppID    uuid.UUID `json:"app_id"`
	OrgID    uuid.UUID `json:"org_id"`
	Name     string    `json:"name"`
	Priority int32     `json:"priority"`
}

// =================================================================
// POLICIES
// Evaluated in priority order (lowest first).
// First matching policy wins — OR logic between policies.
// =================================================================
func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.AppID,
		arg.OrgID,
		arg.Name,
		arg.Priority,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Name,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPolicyRule = `-- name: CreatePolicyRule :one

INSERT INTO policy_rules (policy_id, effect, rule_type, value)
VALUES ($1, $2, $3, $4)
RETURNING id, policy_id, effect, rule_type, value, created_at
`

type CreatePolicyRuleParams struct {
	PolicyID uuid.UUID `json:"policy_id"`
	Effect   string    `json:"effect"`
	RuleType string    `json:"rule_type"`
	Value    string    `json:"value"`
}

// =================================================================
// POLICY RULES
// Flat rules. AND logic implicit within a policy.
// All rules in a policy must match for the policy to apply.
// =================================================================
func (q *Queries) CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, createPolicyRule,
		arg.PolicyID,
		arg.Effect,
		arg.RuleType,
		arg.Value,
	)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Effect,
		&i.RuleType,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllRulesForPolicy = `-- name: DeleteAllRulesForPolicy :exec
DELETE FROM policy_rules
WHERE policy_id = $1
`

// Called before rebuilding a policy's rules on full update.
func (q *Queries) DeleteAllRulesForPolicy(ctx context.Context, policyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRulesForPolicy, policyID)
	return err
}

const deletePolicy = `-- name: DeletePolicy :one
UPDATE policies
SET deleted_at = now(),
    updated_at = now()
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
RETURNING id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at
`

type DeletePolicyParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Soft delete. Rules are cascade-orphaned but retained for audit.
func (q *Queries) DeletePolicy(ctx context.Context, arg DeletePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, deletePolicy, arg.ID, arg.OrgID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Name,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePolicyRule = `-- name: DeletePolicyRule :one
DELETE FROM policy_rules
WHERE id        = $1
  AND policy_id = $2
RETURNING id, policy_id, effect, rule_type, value, created_at
`

type DeletePolicyRuleParams struct {
	ID       uuid.UUID `json:"id"`
	PolicyID uuid.UUID `json:"policy_id"`
}

func (q *Queries) DeletePolicyRule(ctx context.Context, arg DeletePolicyRuleParams) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, deletePolicyRule, arg.ID, arg.PolicyID)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Effect,
		&i.RuleType,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at FROM policies
WHERE id         = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPolicyByID(ctx context.Context, id uuid.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Name,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPolicyByIDAndOrg = `-- name: GetPolicyByIDAndOrg :one
SELECT id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at FROM policies
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
`

type GetPolicyByIDAndOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetPolicyByIDAndOrg(ctx context.Context, arg GetPolicyByIDAndOrgParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByIDAndOrg, arg.ID, arg.OrgID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Name,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPolicyRuleByID = `-- name: GetPolicyRuleByID :one
SELECT id, policy_id, effect, rule_type, value, created_at FROM policy_rules
WHERE id = $1
`

func (q *Queries) GetPolicyRuleByID(ctx context.Context, id uuid.UUID) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, getPolicyRuleByID, id)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Effect,
		&i.RuleType,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPoliciesByOrg = `-- name: ListAllPoliciesByOrg :many
SELECT id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at FROM policies
WHERE org_id     = $1
  AND deleted_at IS NULL
ORDER BY app_id, priority ASC
`

// Used by dashboard to display all policies across all apps.
func (q *Queries) ListAllPoliciesByOrg(ctx context.Context, orgID uuid.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listAllPoliciesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.OrgID,
			&i.Name,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByApp = `-- name: ListPoliciesByApp :many
SELECT id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at FROM policies
WHERE app_id     = $1
  AND is_active  = true
  AND deleted_at IS NULL
ORDER BY priority ASC
`

// Returns active policies in priority order.
// Used by Gateway policy sync to build local eval bundle.
func (q *Queries) ListPoliciesByApp(ctx context.Context, appID uuid.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.OrgID,
			&i.Name,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByPolicies = `-- name: ListRulesByPolicies :many
SELECT id, policy_id, effect, rule_type, value, created_at FROM policy_rules
WHERE policy_id = ANY($1::uuid[])
ORDER BY policy_id, created_at ASC
`

// Batch fetch for policy sync — all rules for multiple policies at once.
// Avoids N+1 when syncing a full app policy bundle.
func (q *Queries) ListRulesByPolicies(ctx context.Context, dollar_1 []uuid.UUID) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, listRulesByPolicies, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyRule{}
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Effect,
			&i.RuleType,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByPolicy = `-- name: ListRulesByPolicy :many
SELECT id, policy_id, effect, rule_type, value, created_at FROM policy_rules
WHERE policy_id = $1
ORDER BY created_at ASC
`

// Core of the policy sync bundle. Called per policy.
func (q *Queries) ListRulesByPolicy(ctx context.Context, policyID uuid.UUID) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, listRulesByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyRule{}
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Effect,
			&i.RuleType,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET name       = $3,
    priority   = $4,
    is_active  = $5,
    updated_at = now()
WHERE id         = $1
  AND org_id     = $2
  AND deleted_at IS NULL
RETURNING id, app_id, org_id, name, priority, is_active, created_at, updated_at, deleted_at
`

type UpdatePolicyParams struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	Name     string    `json:"name"`
	Priority int32     `json:"priority"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Priority,
		arg.IsActive,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Name,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
