// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = $1 AND org_id = $2
`

type DeletePolicyParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeletePolicy(ctx context.Context, arg DeletePolicyParams) error {
	_, err := q.db.Exec(ctx, deletePolicy, arg.ID, arg.OrgID)
	return err
}

const deletePolicyCondition = `-- name: DeletePolicyCondition :exec
DELETE FROM policy_conditions WHERE policy_id = $1
`

func (q *Queries) DeletePolicyCondition(ctx context.Context, policyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicyCondition, policyID)
	return err
}

const deletePolicyResources = `-- name: DeletePolicyResources :exec
DELETE FROM policy_resources WHERE policy_id = $1
`

func (q *Queries) DeletePolicyResources(ctx context.Context, policyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicyResources, policyID)
	return err
}

const deletePolicySubjects = `-- name: DeletePolicySubjects :exec
DELETE FROM policy_subjects WHERE policy_id = $1
`

func (q *Queries) DeletePolicySubjects(ctx context.Context, policyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicySubjects, policyID)
	return err
}

const getLatestPolicyVersion = `-- name: GetLatestPolicyVersion :one
SELECT COALESCE(MAX(version), 0)::bigint AS version
FROM policy_mutations
WHERE org_id = $1
`

func (q *Queries) GetLatestPolicyVersion(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestPolicyVersion, orgID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getMutationsSince = `-- name: GetMutationsSince :many
SELECT version, org_id, policy_id, op, rule_snapshot, mutated_by, mutated_at
FROM policy_mutations
WHERE org_id = $1 AND version > $2
ORDER BY version ASC
`

type GetMutationsSinceParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	Version int64     `json:"version"`
}

func (q *Queries) GetMutationsSince(ctx context.Context, arg GetMutationsSinceParams) ([]PolicyMutation, error) {
	rows, err := q.db.Query(ctx, getMutationsSince, arg.OrgID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyMutation{}
	for rows.Next() {
		var i PolicyMutation
		if err := rows.Scan(
			&i.Version,
			&i.OrgID,
			&i.PolicyID,
			&i.Op,
			&i.RuleSnapshot,
			&i.MutatedBy,
			&i.MutatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT 
    p.id, p.org_id, p.name, p.description, p.effect, p.priority, 
    p.enabled, p.version, p.created_by, p.created_at, p.updated_at
FROM policies p
WHERE p.id = $1 AND p.org_id = $2
`

type GetPolicyByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetPolicyByID(ctx context.Context, arg GetPolicyByIDParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, arg.ID, arg.OrgID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Effect,
		&i.Priority,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyCondition = `-- name: GetPolicyCondition :one
SELECT policy_id, condition_tree, updated_at
FROM policy_conditions
WHERE policy_id = $1
`

func (q *Queries) GetPolicyCondition(ctx context.Context, policyID uuid.UUID) (PolicyCondition, error) {
	row := q.db.QueryRow(ctx, getPolicyCondition, policyID)
	var i PolicyCondition
	err := row.Scan(&i.PolicyID, &i.ConditionTree, &i.UpdatedAt)
	return i, err
}

const getPolicyResources = `-- name: GetPolicyResources :many
SELECT policy_id, resource_type, resource_value
FROM policy_resources
WHERE policy_id = $1
`

func (q *Queries) GetPolicyResources(ctx context.Context, policyID uuid.UUID) ([]PolicyResource, error) {
	rows, err := q.db.Query(ctx, getPolicyResources, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyResource{}
	for rows.Next() {
		var i PolicyResource
		if err := rows.Scan(&i.PolicyID, &i.ResourceType, &i.ResourceValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicySubjects = `-- name: GetPolicySubjects :many
SELECT policy_id, subject_type, subject_value
FROM policy_subjects
WHERE policy_id = $1
`

func (q *Queries) GetPolicySubjects(ctx context.Context, policyID uuid.UUID) ([]PolicySubject, error) {
	rows, err := q.db.Query(ctx, getPolicySubjects, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicySubject{}
	for rows.Next() {
		var i PolicySubject
		if err := rows.Scan(&i.PolicyID, &i.SubjectType, &i.SubjectValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO policies (
    id, org_id, name, description, effect, priority, enabled, version, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, description, effect, priority, enabled, version, created_by, created_at, updated_at
`

type InsertPolicyParams struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       uuid.UUID   `json:"org_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Effect      string      `json:"effect"`
	Priority    pgtype.Int4 `json:"priority"`
	Enabled     bool        `json:"enabled"`
	Version     int64       `json:"version"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Effect,
		arg.Priority,
		arg.Enabled,
		arg.Version,
		arg.CreatedBy,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Effect,
		&i.Priority,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPolicyAuditLog = `-- name: InsertPolicyAuditLog :exec
INSERT INTO policy_audit_log (
    org_id, policy_id, action, actor_id, actor_email, old_state, new_state, ip_address, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPolicyAuditLogParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	PolicyID   pgtype.Text `json:"policy_id"`
	Action     string      `json:"action"`
	ActorID    string      `json:"actor_id"`
	ActorEmail pgtype.Text `json:"actor_email"`
	OldState   []byte      `json:"old_state"`
	NewState   []byte      `json:"new_state"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertPolicyAuditLog(ctx context.Context, arg InsertPolicyAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertPolicyAuditLog,
		arg.OrgID,
		arg.PolicyID,
		arg.Action,
		arg.ActorID,
		arg.ActorEmail,
		arg.OldState,
		arg.NewState,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertPolicyCondition = `-- name: InsertPolicyCondition :exec
INSERT INTO policy_conditions (policy_id, condition_tree)
VALUES ($1, $2)
ON CONFLICT (policy_id) DO UPDATE SET condition_tree = EXCLUDED.condition_tree, updated_at = NOW()
`

type InsertPolicyConditionParams struct {
	PolicyID      uuid.UUID       `json:"policy_id"`
	ConditionTree json.RawMessage `json:"condition_tree"`
}

func (q *Queries) InsertPolicyCondition(ctx context.Context, arg InsertPolicyConditionParams) error {
	_, err := q.db.Exec(ctx, insertPolicyCondition, arg.PolicyID, arg.ConditionTree)
	return err
}

const insertPolicyMutation = `-- name: InsertPolicyMutation :one
INSERT INTO policy_mutations (org_id, policy_id, op, rule_snapshot, mutated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING version
`

type InsertPolicyMutationParams struct {
	OrgID        uuid.UUID       `json:"org_id"`
	PolicyID     uuid.UUID       `json:"policy_id"`
	Op           string          `json:"op"`
	RuleSnapshot json.RawMessage `json:"rule_snapshot"`
	MutatedBy    pgtype.UUID     `json:"mutated_by"`
}

func (q *Queries) InsertPolicyMutation(ctx context.Context, arg InsertPolicyMutationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPolicyMutation,
		arg.OrgID,
		arg.PolicyID,
		arg.Op,
		arg.RuleSnapshot,
		arg.MutatedBy,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const insertPolicyResource = `-- name: InsertPolicyResource :exec
INSERT INTO policy_resources (policy_id, resource_type, resource_value)
VALUES ($1, $2, $3)
ON CONFLICT (policy_id, resource_type, resource_value) DO NOTHING
`

type InsertPolicyResourceParams struct {
	PolicyID      uuid.UUID `json:"policy_id"`
	ResourceType  string    `json:"resource_type"`
	ResourceValue string    `json:"resource_value"`
}

func (q *Queries) InsertPolicyResource(ctx context.Context, arg InsertPolicyResourceParams) error {
	_, err := q.db.Exec(ctx, insertPolicyResource, arg.PolicyID, arg.ResourceType, arg.ResourceValue)
	return err
}

const insertPolicySubject = `-- name: InsertPolicySubject :exec
INSERT INTO policy_subjects (policy_id, subject_type, subject_value)
VALUES ($1, $2, $3)
ON CONFLICT (policy_id, subject_type, subject_value) DO NOTHING
`

type InsertPolicySubjectParams struct {
	PolicyID     uuid.UUID `json:"policy_id"`
	SubjectType  string    `json:"subject_type"`
	SubjectValue string    `json:"subject_value"`
}

func (q *Queries) InsertPolicySubject(ctx context.Context, arg InsertPolicySubjectParams) error {
	_, err := q.db.Exec(ctx, insertPolicySubject, arg.PolicyID, arg.SubjectType, arg.SubjectValue)
	return err
}

const listPoliciesByOrg = `-- name: ListPoliciesByOrg :many
SELECT 
    p.id, p.org_id, p.name, p.description, p.effect, p.priority, 
    p.enabled, p.version, p.created_by, p.created_at, p.updated_at
FROM policies p
WHERE p.org_id = $1
ORDER BY p.effect DESC, p.priority DESC, p.id
`

func (q *Queries) ListPoliciesByOrg(ctx context.Context, orgID uuid.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Effect,
			&i.Priority,
			&i.Enabled,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    effect = COALESCE($5, effect),
    priority = COALESCE($6, priority),
    enabled = COALESCE($7, enabled),
    version = $2,
    updated_at = NOW()
WHERE id = $1 AND org_id = $8
RETURNING id, org_id, name, description, effect, priority, enabled, version, created_by, created_at, updated_at
`

type UpdatePolicyParams struct {
	ID          uuid.UUID   `json:"id"`
	Version     int64       `json:"version"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Effect      pgtype.Text `json:"effect"`
	Priority    pgtype.Int4 `json:"priority"`
	Enabled     pgtype.Bool `json:"enabled"`
	OrgID       pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.Version,
		arg.Name,
		arg.Description,
		arg.Effect,
		arg.Priority,
		arg.Enabled,
		arg.OrgID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Effect,
		&i.Priority,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
