// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Called at the end of /verify-otp during setup. Creates the org and links it.
	ActivateAdmin(ctx context.Context, arg ActivateAdminParams) (Admin, error)
	AddAppIdPMapping(ctx context.Context, arg AddAppIdPMappingParams) (AppIdpMapping, error)
	// Called once during SSO binding confirmation flow.
	// Stores sub claim, links IdP config, marks sso_bound.
	BindAdminSSO(ctx context.Context, arg BindAdminSSOParams) (Admin, error)
	// =============================================================================
	// Snapshot Builder (for mutation log)
	// =============================================================================
	BuildPolicyRuleSnapshot(ctx context.Context, arg BuildPolicyRuleSnapshotParams) (json.RawMessage, error)
	// Uses pgx COPY protocol for high-throughput batch inserts.
	// Gateway drains its local buffer to CP every 10s.
	BulkCreateAccessLogs(ctx context.Context, arg []BulkCreateAccessLogsParams) (int64, error)
	// Dashboard summary counts.
	CountAccessLogsByResult(ctx context.Context, arg CountAccessLogsByResultParams) (CountAccessLogsByResultRow, error)
	// Used before revoking an owner — must always have at least one.
	CountOwnersByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error)
	// =================================================================
	// ACCESS LOGS
	// Written async by Gateway in batches. CP never in traffic path.
	// =================================================================
	CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (AccessLog, error)
	// =================================================================
	// AUTH
	// =================================================================
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	// =================================================================
	// APPS
	// =================================================================
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	// =================================================================
	// AUDIT LOGS
	// Append-only. Never update or delete.
	// =================================================================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// =================================================================
	// CRL ENTRIES
	// =================================================================
	CreateCRLEntry(ctx context.Context, arg CreateCRLEntryParams) (CrlEntry, error)
	CreateComponentCertificate(ctx context.Context, arg CreateComponentCertificateParams) (ComponentCertificate, error)
	// =================================================================
	// CONNECTORS
	// token_hash: SHA-256 of connector enrollment token.
	// =================================================================
	CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error)
	// =================================================================
	// GATEWAYS
	// token_hash: SHA-256 of enrollment token. Never plaintext.
	// =================================================================
	CreateGateway(ctx context.Context, arg CreateGatewayParams) (Gateway, error)
	CreateGatewayEvent(ctx context.Context, arg CreateGatewayEventParams) (GatewayEvent, error)
	CreateGatewayEventAcks(ctx context.Context, arg CreateGatewayEventAcksParams) (GatewayEventsAck, error)
	// =================================================================
	// IDP CONFIGS
	// client_secret must be AES-256-GCM encrypted before insert.
	// Never store or return plaintext secrets.
	// =================================================================
	CreateIDPConfig(ctx context.Context, arg CreateIDPConfigParams) (IdpConfig, error)
	// =================================================================
	// ORGS
	// =================================================================
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error)
	CreateSetupToken(ctx context.Context, arg CreateSetupTokenParams) (AdminSetupToken, error)
	CreateUserSessionForGateway(ctx context.Context, arg CreateUserSessionForGatewayParams) (UserSession, error)
	DeactivateCACert(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Soft delete. Policies referencing this app remain for audit history.
	DeleteApp(ctx context.Context, arg DeleteAppParams) (App, error)
	// Housekeeping. Run periodically via background job.
	DeleteExpiredAdminSessions(ctx context.Context) error
	// Soft delete. Cannot delete if it is the only verified active IdP
	// — enforce this check in the service layer before calling.
	DeleteIDPConfig(ctx context.Context, arg DeleteIDPConfigParams) (IdpConfig, error)
	// Soft delete only. Hard delete is a manual ops action.
	DeleteOrg(ctx context.Context, id uuid.UUID) (Org, error)
	DeletePolicy(ctx context.Context, arg DeletePolicyParams) error
	DeletePolicyCondition(ctx context.Context, policyID uuid.UUID) error
	DeletePolicyResources(ctx context.Context, policyID uuid.UUID) error
	DeletePolicySubjects(ctx context.Context, policyID uuid.UUID) error
	EnrollConnector(ctx context.Context, tokenHash string) (Connector, error)
	EnrollGateway(ctx context.Context, tokenHash string) (Gateway, error)
	GetActiveCACert(ctx context.Context, arg GetActiveCACertParams) (GetActiveCACertRow, error)
	// Returns the active (non-revoked) CA cert of a given type.
	GetActiveCACertByType(ctx context.Context, type_ string) (CaCertificate, error)
	// Returns the current valid cert for a gateway or connector.
	GetActiveComponentCert(ctx context.Context, arg GetActiveComponentCertParams) (ComponentCertificate, error)
	// Returns all valid certs of a given type.
	GetActiveComponentCertByType(ctx context.Context, componentType string) (ComponentCertificate, error)
	GetActiveConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error)
	GetActiveGatewayByID(ctx context.Context, id uuid.UUID) (Gateway, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	// Used at password login. Returns record regardless of sso_only
	// so caller can check sso_only and reject if needed.
	GetAdminByEmailWithOrg(ctx context.Context, arg GetAdminByEmailWithOrgParams) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	// =================================================================
	// ADMINS
	// =================================================================
	// Used at OIDC callback. Matches on permanent IdP sub claim.
	GetAdminByIDPSubject(ctx context.Context, arg GetAdminByIDPSubjectParams) (Admin, error)
	// Hot path: called on every dashboard request.
	// Returns session only if valid (not expired, not revoked).
	GetAdminSession(ctx context.Context, refreshToken string) (AdminSession, error)
	GetAppByID(ctx context.Context, id uuid.UUID) (App, error)
	GetAppByIDAndOrg(ctx context.Context, arg GetAppByIDAndOrgParams) (App, error)
	// Called by Gateway to resolve subdomain to app during routing.
	GetAppBySubdomain(ctx context.Context, arg GetAppBySubdomainParams) (App, error)
	// Gateway calls this to check if a presented cert is revoked.
	GetCRLEntryBySerial(ctx context.Context, serialNumber string) (CrlEntry, error)
	GetConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error)
	GetConnectorByIDAndOrg(ctx context.Context, arg GetConnectorByIDAndOrgParams) (Connector, error)
	// Called on connector → gateway auth.
	GetConnectorByTokenHash(ctx context.Context, tokenHash string) (Connector, error)
	GetGatewayByID(ctx context.Context, id uuid.UUID) (Gateway, error)
	GetGatewayByIDAndOrg(ctx context.Context, arg GetGatewayByIDAndOrgParams) (Gateway, error)
	// Called on every Gateway → CP request (heartbeat, policy sync).
	// Keep this fast — it is on the service path.
	GetGatewayByTokenHash(ctx context.Context, tokenHash string) (Gateway, error)
	GetIDPConfigByID(ctx context.Context, id uuid.UUID) (IdpConfig, error)
	// Always scope to org — never allow cross-org access.
	GetIDPConfigByIDAndOrg(ctx context.Context, arg GetIDPConfigByIDAndOrgParams) (IdpConfig, error)
	GetLastAckedSeqForGateway(ctx context.Context, gatewayID uuid.UUID) (int64, error)
	GetLastEventSeqForGateway(ctx context.Context, gatewayID uuid.UUID) (int64, error)
	GetLatestPolicyVersion(ctx context.Context, orgID uuid.UUID) (int64, error)
	GetMutationsSince(ctx context.Context, arg GetMutationsSinceParams) ([]GetMutationsSinceRow, error)
	GetNextPolicySequence(ctx context.Context, arg GetNextPolicySequenceParams) (int32, error)
	// Used by Gateway to resolve incoming hostname to org (v2)
	GetOrgByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Org, error)
	GetOrgByID(ctx context.Context, id uuid.UUID) (Org, error)
	GetOrgBySlug(ctx context.Context, slug string) (Org, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPolicyByID(ctx context.Context, arg GetPolicyByIDParams) (Policy, error)
	GetPolicyCondition(ctx context.Context, policyID uuid.UUID) (PolicyCondition, error)
	GetPolicyMutation(ctx context.Context, arg GetPolicyMutationParams) (GetPolicyMutationRow, error)
	GetPolicyResources(ctx context.Context, policyID uuid.UUID) ([]PolicyResource, error)
	GetPolicySubjects(ctx context.Context, policyID uuid.UUID) ([]PolicySubject, error)
	GetPolicyWithDetails(ctx context.Context, arg GetPolicyWithDetailsParams) (GetPolicyWithDetailsRow, error)
	GetSetupToken(ctx context.Context, tokenHash string) (AdminSetupToken, error)
	GetUserActiveSession(ctx context.Context, arg GetUserActiveSessionParams) ([]UserSession, error)
	GetUserSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetValidCompCert(ctx context.Context, arg GetValidCompCertParams) (GetValidCompCertRow, error)
	InsertCACert(ctx context.Context, arg InsertCACertParams) (uuid.UUID, error)
	// =============================================================================
	// Normalized Policy CRUD
	// =============================================================================
	InsertPolicy(ctx context.Context, arg InsertPolicyParams) (Policy, error)
	// =============================================================================
	// Audit
	// =============================================================================
	InsertPolicyAuditLog(ctx context.Context, arg InsertPolicyAuditLogParams) error
	InsertPolicyCondition(ctx context.Context, arg InsertPolicyConditionParams) error
	InsertPolicyMutation(ctx context.Context, arg InsertPolicyMutationParams) (InsertPolicyMutationRow, error)
	InsertPolicyResource(ctx context.Context, arg InsertPolicyResourceParams) error
	// =============================================================================
	// Subjects, Resources, Conditions
	// =============================================================================
	InsertPolicySubject(ctx context.Context, arg InsertPolicySubjectParams) error
	ListAccessLogsByApp(ctx context.Context, arg ListAccessLogsByAppParams) ([]AccessLog, error)
	ListAccessLogsByOrg(ctx context.Context, arg ListAccessLogsByOrgParams) ([]AccessLog, error)
	ListActiveCACerts(ctx context.Context, arg ListActiveCACertsParams) ([]ListActiveCACertsRow, error)
	// -- name: ListActiveConnectorsByGateway :many
	// -- Called on gateway → connector auth.
	// SELECT * FROM connectors
	// WHERE gateway_id = $1
	//   AND is_active = true
	//   AND revoked_at IS NULL;
	// Called on gateway → connector auth.
	ListActiveConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) ([]Connector, error)
	ListActiveGatewaysByOrg(ctx context.Context, orgID uuid.UUID) ([]Gateway, error)
	ListAdminsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Admin, error)
	ListAppIdPs(ctx context.Context, appID uuid.UUID) ([]IdpConfig, error)
	ListAppsByConnector(ctx context.Context, connectorID pgtype.UUID) ([]App, error)
	ListAppsByOrg(ctx context.Context, orgID uuid.UUID) ([]App, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error)
	ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]AuditLog, error)
	// Gateway fetches full CRL on startup and after each sync.
	ListCRLEntries(ctx context.Context) ([]CrlEntry, error)
	ListConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) ([]Connector, error)
	ListConnectorsByOrg(ctx context.Context, orgID uuid.UUID) ([]Connector, error)
	// Dashboard denied requests view.
	ListDeniedAccessLogs(ctx context.Context, arg ListDeniedAccessLogsParams) ([]AccessLog, error)
	ListGatewaysByOrg(ctx context.Context, orgID uuid.UUID) ([]Gateway, error)
	ListIDPConfigsByOrg(ctx context.Context, orgID uuid.UUID) ([]IdpConfig, error)
	ListPoliciesByOrg(ctx context.Context, orgID uuid.UUID) ([]Policy, error)
	// Called after owner completes SSO binding confirmation flow.
	MarkIDPConfigVerified(ctx context.Context, arg MarkIDPConfigVerifiedParams) (IdpConfig, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkSetupTokenUsed(ctx context.Context, id uuid.UUID) error
	// Called after owner confirms SSO migration.
	// Clears password_hash — no going back without owner action.
	MigrateAdminToSSOOnly(ctx context.Context, id uuid.UUID) (Admin, error)
	// Retention policy. Default 90 days. Run via background job.
	PurgeOldAccessLogs(ctx context.Context, dollar_1 pgtype.Text) error
	ReCreateConnector(ctx context.Context, arg ReCreateConnectorParams) (Connector, error)
	ReCreateGateway(ctx context.Context, arg ReCreateGatewayParams) (Gateway, error)
	RegisterCompCert(ctx context.Context, arg RegisterCompCertParams) (ComponentCertificate, error)
	RevokeActiveUserSession(ctx context.Context, id uuid.UUID) (UserSession, error)
	RevokeAdmin(ctx context.Context, id uuid.UUID) (Admin, error)
	// Single session revocation (logout).
	RevokeAdminSession(ctx context.Context, id uuid.UUID) error
	// Revoke all sessions for an admin (e.g. role changed, account suspended, passchange/account compromise).
	RevokeAllAdminSessionsForAdmin(ctx context.Context, adminID uuid.UUID) error
	// Nuclear option — used when org SSO config changes.
	RevokeAllAdminSessionsForOrg(ctx context.Context, orgID uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) ([]UserSession, error)
	RevokeCompCert(ctx context.Context, arg RevokeCompCertParams) (ComponentCertificate, error)
	RevokeConnector(ctx context.Context, arg RevokeConnectorParams) (Connector, error)
	// Called when a gateway is revoked — cascade revoke all its connectors.
	RevokeConnectorsByGateway(ctx context.Context, gatewayID uuid.UUID) error
	// Immediately disconnects gateway. Token becomes invalid.
	RevokeGateway(ctx context.Context, arg RevokeGatewayParams) (Gateway, error)
	// Sets custom domain and generates a verification token.
	// domain_verified stays false until DNS challenge passes.
	SetOrgCustomDomain(ctx context.Context, arg SetOrgCustomDomainParams) (Org, error)
	UpdateAdminOTP(ctx context.Context, arg UpdateAdminOTPParams) (Admin, error)
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	// Owner only action.
	UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) (Admin, error)
	UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error)
	UpdateConnectorStatus(ctx context.Context, arg UpdateConnectorStatusParams) (Connector, error)
	UpdateGatewayBinaryVersion(ctx context.Context, arg UpdateGatewayBinaryVersionParams) (Gateway, error)
	// Called every 30s by Gateway. Updates last_heartbeat and version.
	UpdateGatewayHeartbeat(ctx context.Context, id uuid.UUID) (Gateway, error)
	UpdateGatewayStatus(ctx context.Context, arg UpdateGatewayStatusParams) (Gateway, error)
	// Updating secrets rotates the encrypted value.
	UpdateIDPConfig(ctx context.Context, arg UpdateIDPConfigParams) (IdpConfig, error)
	UpdateMutationSignature(ctx context.Context, arg UpdateMutationSignatureParams) error
	UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) (Org, error)
	UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error)
	// Called after CP confirms the DNS TXT record is present.
	VerifyOrgCustomDomain(ctx context.Context, arg VerifyOrgCustomDomainParams) (Org, error)
}

var _ Querier = (*Queries)(nil)
