// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocations_certs_logs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateAccessLogsParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	IdpConfigID pgtype.UUID `json:"idp_config_id"`
	UserEmail   pgtype.Text `json:"user_email"`
	Method      pgtype.Text `json:"method"`
	Path        pgtype.Text `json:"path"`
	Status      pgtype.Int4 `json:"status"`
	LatencyMs   pgtype.Int4 `json:"latency_ms"`
	Ip          pgtype.Text `json:"ip"`
	Result      string      `json:"result"`
	DenyReason  pgtype.Text `json:"deny_reason"`
}

const countAccessLogsByResult = `-- name: CountAccessLogsByResult :one
SELECT
    COUNT(*) FILTER (WHERE result = 'allowed') AS allowed_count,
    COUNT(*) FILTER (WHERE result = 'denied')  AS denied_count
FROM access_logs
WHERE org_id     = $1
  AND created_at >= $2
  AND created_at <= $3
`

type CountAccessLogsByResultParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type CountAccessLogsByResultRow struct {
	AllowedCount int64 `json:"allowed_count"`
	DeniedCount  int64 `json:"denied_count"`
}

// Dashboard summary counts.
func (q *Queries) CountAccessLogsByResult(ctx context.Context, arg CountAccessLogsByResultParams) (CountAccessLogsByResultRow, error) {
	row := q.db.QueryRow(ctx, countAccessLogsByResult, arg.OrgID, arg.CreatedAt, arg.CreatedAt_2)
	var i CountAccessLogsByResultRow
	err := row.Scan(&i.AllowedCount, &i.DeniedCount)
	return i, err
}

const createAccessLog = `-- name: CreateAccessLog :one

INSERT INTO access_logs (
    org_id, app_id, idp_config_id, user_email,
    method, path, status, latency_ms,
    ip, result, deny_reason
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at
`

type CreateAccessLogParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	IdpConfigID pgtype.UUID `json:"idp_config_id"`
	UserEmail   pgtype.Text `json:"user_email"`
	Method      pgtype.Text `json:"method"`
	Path        pgtype.Text `json:"path"`
	Status      pgtype.Int4 `json:"status"`
	LatencyMs   pgtype.Int4 `json:"latency_ms"`
	Ip          pgtype.Text `json:"ip"`
	Result      string      `json:"result"`
	DenyReason  pgtype.Text `json:"deny_reason"`
}

// =================================================================
// ACCESS LOGS
// Written async by Gateway in batches. CP never in traffic path.
// =================================================================
func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (AccessLog, error) {
	row := q.db.QueryRow(ctx, createAccessLog,
		arg.OrgID,
		arg.AppID,
		arg.IdpConfigID,
		arg.UserEmail,
		arg.Method,
		arg.Path,
		arg.Status,
		arg.LatencyMs,
		arg.Ip,
		arg.Result,
		arg.DenyReason,
	)
	var i AccessLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.IdpConfigID,
		&i.UserEmail,
		&i.Method,
		&i.Path,
		&i.Status,
		&i.LatencyMs,
		&i.Ip,
		&i.Result,
		&i.DenyReason,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (org_id, actor_id, action, target_type, target_id, details, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, actor_id, action, target_type, target_id, details, ip, created_at
`

type CreateAuditLogParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Details    []byte      `json:"details"`
	Ip         pgtype.Text `json:"ip"`
}

// =================================================================
// AUDIT LOGS
// Append-only. Never update or delete.
// =================================================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.Ip,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Details,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const createCACertificate = `-- name: CreateCACertificate :one

INSERT INTO ca_certificates (name, type, cert_pem, serial_number, subject, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, type, cert_pem, serial_number, subject, issued_at, expires_at, revoked_at, created_at
`

type CreateCACertificateParams struct {
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	CertPem      string    `json:"cert_pem"`
	SerialNumber string    `json:"serial_number"`
	Subject      string    `json:"subject"`
	IssuedAt     time.Time `json:"issued_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

// =================================================================
// CERTIFICATES — CA
// =================================================================
func (q *Queries) CreateCACertificate(ctx context.Context, arg CreateCACertificateParams) (CaCertificate, error) {
	row := q.db.QueryRow(ctx, createCACertificate,
		arg.Name,
		arg.Type,
		arg.CertPem,
		arg.SerialNumber,
		arg.Subject,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i CaCertificate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CertPem,
		&i.SerialNumber,
		&i.Subject,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCRLEntry = `-- name: CreateCRLEntry :one








INSERT INTO crl_entries (cert_id, serial_number, reason)
VALUES ($1, $2, $3)
RETURNING id, cert_id, serial_number, revoked_at, reason
`

type CreateCRLEntryParams struct {
	CertID       uuid.UUID `json:"cert_id"`
	SerialNumber string    `json:"serial_number"`
	Reason       string    `json:"reason"`
}

// -- =================================================================
// -- CSR REQUESTS
// -- =================================================================
// -- name: CreateCSRRequest :one
// INSERT INTO csr_requests (org_id, component_type, component_id, csr_pem)
// VALUES ($1, $2, $3, $4)
// RETURNING *;
// -- name: GetCSRRequest :one
// SELECT * FROM csr_requests
// WHERE id = $1;
// -- name: MarkCSRSigned :one
// UPDATE csr_requests
// SET status         = 'signed',
//
//	signed_cert_id = $2,
//	processed_at   = now()
//
// WHERE id           = $1
//
//	AND status       = 'pending'
//
// RETURNING *;
// -- name: MarkCSRRejected :one
// UPDATE csr_requests
// SET status       = 'rejected',
//
//	processed_at = now()
//
// WHERE id         = $1
//
//	AND status     = 'pending'
//
// RETURNING *;
// -- name: ListPendingCSRs :many
// SELECT * FROM csr_requests
// WHERE status = 'pending'
// ORDER BY created_at ASC;
// =================================================================
// CRL ENTRIES
// =================================================================
func (q *Queries) CreateCRLEntry(ctx context.Context, arg CreateCRLEntryParams) (CrlEntry, error) {
	row := q.db.QueryRow(ctx, createCRLEntry, arg.CertID, arg.SerialNumber, arg.Reason)
	var i CrlEntry
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.SerialNumber,
		&i.RevokedAt,
		&i.Reason,
	)
	return i, err
}

const createComponentCertificate = `-- name: CreateComponentCertificate :one

INSERT INTO component_certificates (
    org_id, component_type, component_id, ca_id,
    cert_pem, serial_number, subject, san,
    issued_at, expires_at, rotation_of
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, component_type, component_id, ca_id, cert_pem, serial_number, subject, san, issued_at, expires_at, revoked_at, revoke_reason, rotation_of, created_at
`

type CreateComponentCertificateParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ComponentType string      `json:"component_type"`
	ComponentID   pgtype.UUID `json:"component_id"`
	CaID          uuid.UUID   `json:"ca_id"`
	CertPem       string      `json:"cert_pem"`
	SerialNumber  string      `json:"serial_number"`
	Subject       string      `json:"subject"`
	San           []string    `json:"san"`
	IssuedAt      time.Time   `json:"issued_at"`
	ExpiresAt     time.Time   `json:"expires_at"`
	RotationOf    pgtype.UUID `json:"rotation_of"`
}

// =================================================================
// CERTIFICATES — COMPONENTS
// =================================================================
func (q *Queries) CreateComponentCertificate(ctx context.Context, arg CreateComponentCertificateParams) (ComponentCertificate, error) {
	row := q.db.QueryRow(ctx, createComponentCertificate,
		arg.OrgID,
		arg.ComponentType,
		arg.ComponentID,
		arg.CaID,
		arg.CertPem,
		arg.SerialNumber,
		arg.Subject,
		arg.San,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RotationOf,
	)
	var i ComponentCertificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ComponentType,
		&i.ComponentID,
		&i.CaID,
		&i.CertPem,
		&i.SerialNumber,
		&i.Subject,
		&i.San,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RotationOf,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCACertByType = `-- name: GetActiveCACertByType :one
SELECT id, name, type, cert_pem, serial_number, subject, issued_at, expires_at, revoked_at, created_at FROM ca_certificates
WHERE type       = $1
  AND revoked_at IS NULL
ORDER BY issued_at DESC
LIMIT 1
`

// Returns the active (non-revoked) CA cert of a given type.
func (q *Queries) GetActiveCACertByType(ctx context.Context, type_ string) (CaCertificate, error) {
	row := q.db.QueryRow(ctx, getActiveCACertByType, type_)
	var i CaCertificate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CertPem,
		&i.SerialNumber,
		&i.Subject,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveComponentCert = `-- name: GetActiveComponentCert :one
SELECT id, org_id, component_type, component_id, ca_id, cert_pem, serial_number, subject, san, issued_at, expires_at, revoked_at, revoke_reason, rotation_of, created_at FROM component_certificates
WHERE component_type = $1
  AND component_id   = $2
  AND revoked_at     IS NULL
ORDER BY issued_at DESC
LIMIT 1
`

type GetActiveComponentCertParams struct {
	ComponentType string      `json:"component_type"`
	ComponentID   pgtype.UUID `json:"component_id"`
}

// Returns the current valid cert for a gateway or connector.
func (q *Queries) GetActiveComponentCert(ctx context.Context, arg GetActiveComponentCertParams) (ComponentCertificate, error) {
	row := q.db.QueryRow(ctx, getActiveComponentCert, arg.ComponentType, arg.ComponentID)
	var i ComponentCertificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ComponentType,
		&i.ComponentID,
		&i.CaID,
		&i.CertPem,
		&i.SerialNumber,
		&i.Subject,
		&i.San,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RotationOf,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveComponentCertByType = `-- name: GetActiveComponentCertByType :one
SELECT id, org_id, component_type, component_id, ca_id, cert_pem, serial_number, subject, san, issued_at, expires_at, revoked_at, revoke_reason, rotation_of, created_at FROM component_certificates
WHERE component_type = $1
  AND revoked_at IS NULL
ORDER BY issued_at DESC
LIMIT 1
`

// Returns all valid certs of a given type.
func (q *Queries) GetActiveComponentCertByType(ctx context.Context, componentType string) (ComponentCertificate, error) {
	row := q.db.QueryRow(ctx, getActiveComponentCertByType, componentType)
	var i ComponentCertificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ComponentType,
		&i.ComponentID,
		&i.CaID,
		&i.CertPem,
		&i.SerialNumber,
		&i.Subject,
		&i.San,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RotationOf,
		&i.CreatedAt,
	)
	return i, err
}

const getCRLEntryBySerial = `-- name: GetCRLEntryBySerial :one
SELECT id, cert_id, serial_number, revoked_at, reason FROM crl_entries
WHERE serial_number = $1
`

// Gateway calls this to check if a presented cert is revoked.
func (q *Queries) GetCRLEntryBySerial(ctx context.Context, serialNumber string) (CrlEntry, error) {
	row := q.db.QueryRow(ctx, getCRLEntryBySerial, serialNumber)
	var i CrlEntry
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.SerialNumber,
		&i.RevokedAt,
		&i.Reason,
	)
	return i, err
}

const listAccessLogsByApp = `-- name: ListAccessLogsByApp :many
SELECT id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at FROM access_logs
WHERE app_id     = $1
  AND org_id     = $2
  AND created_at >= $3
  AND created_at <= $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAccessLogsByAppParams struct {
	AppID       pgtype.UUID `json:"app_id"`
	OrgID       uuid.UUID   `json:"org_id"`
	CreatedAt   time.Time   `json:"created_at"`
	CreatedAt_2 time.Time   `json:"created_at_2"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListAccessLogsByApp(ctx context.Context, arg ListAccessLogsByAppParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, listAccessLogsByApp,
		arg.AppID,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.IdpConfigID,
			&i.UserEmail,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Ip,
			&i.Result,
			&i.DenyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessLogsByOrg = `-- name: ListAccessLogsByOrg :many
SELECT id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at FROM access_logs
WHERE org_id     = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAccessLogsByOrgParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListAccessLogsByOrg(ctx context.Context, arg ListAccessLogsByOrgParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, listAccessLogsByOrg,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.IdpConfigID,
			&i.UserEmail,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Ip,
			&i.Result,
			&i.DenyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, org_id, actor_id, action, target_type, target_id, details, ip, created_at FROM audit_logs
WHERE org_id     = $1
  AND actor_id   = $2
  AND created_at >= $3
  AND created_at <= $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsByActorParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	CreatedAt   time.Time   `json:"created_at"`
	CreatedAt_2 time.Time   `json:"created_at_2"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor,
		arg.OrgID,
		arg.ActorID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, org_id, actor_id, action, target_type, target_id, details, ip, created_at FROM audit_logs
WHERE org_id     = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsByOrgParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTarget = `-- name: ListAuditLogsByTarget :many
SELECT id, org_id, actor_id, action, target_type, target_id, details, ip, created_at FROM audit_logs
WHERE org_id      = $1
  AND target_type = $2
  AND target_id   = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsByTargetParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTarget,
		arg.OrgID,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCACertificates = `-- name: ListCACertificates :many
SELECT id, name, type, cert_pem, serial_number, subject, issued_at, expires_at, revoked_at, created_at FROM ca_certificates
ORDER BY issued_at DESC
`

func (q *Queries) ListCACertificates(ctx context.Context) ([]CaCertificate, error) {
	rows, err := q.db.Query(ctx, listCACertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaCertificate{}
	for rows.Next() {
		var i CaCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CertPem,
			&i.SerialNumber,
			&i.Subject,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCRLEntries = `-- name: ListCRLEntries :many
SELECT id, cert_id, serial_number, revoked_at, reason FROM crl_entries
ORDER BY revoked_at DESC
`

// Gateway fetches full CRL on startup and after each sync.
func (q *Queries) ListCRLEntries(ctx context.Context) ([]CrlEntry, error) {
	rows, err := q.db.Query(ctx, listCRLEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrlEntry{}
	for rows.Next() {
		var i CrlEntry
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.SerialNumber,
			&i.RevokedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeniedAccessLogs = `-- name: ListDeniedAccessLogs :many
SELECT id, org_id, app_id, idp_config_id, user_email, method, path, status, latency_ms, ip, result, deny_reason, created_at FROM access_logs
WHERE org_id     = $1
  AND result     = 'denied'
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListDeniedAccessLogsParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

// Dashboard denied requests view.
func (q *Queries) ListDeniedAccessLogs(ctx context.Context, arg ListDeniedAccessLogsParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, listDeniedAccessLogs,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.IdpConfigID,
			&i.UserEmail,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.Ip,
			&i.Result,
			&i.DenyReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringComponentCerts = `-- name: ListExpiringComponentCerts :many
SELECT id, org_id, component_type, component_id, ca_id, cert_pem, serial_number, subject, san, issued_at, expires_at, revoked_at, revoke_reason, rotation_of, created_at FROM component_certificates
WHERE expires_at   < now() + ($1 || ' days')::interval
  AND revoked_at   IS NULL
ORDER BY expires_at ASC
`

// Used by background job to alert before expiry.
// Returns certs expiring within the next $1 days.
func (q *Queries) ListExpiringComponentCerts(ctx context.Context, dollar_1 pgtype.Text) ([]ComponentCertificate, error) {
	rows, err := q.db.Query(ctx, listExpiringComponentCerts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentCertificate{}
	for rows.Next() {
		var i ComponentCertificate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ComponentType,
			&i.ComponentID,
			&i.CaID,
			&i.CertPem,
			&i.SerialNumber,
			&i.Subject,
			&i.San,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.RotationOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldAccessLogs = `-- name: PurgeOldAccessLogs :exec
DELETE FROM access_logs
WHERE created_at < now() - ($1 || ' days')::interval
`

// Retention policy. Default 90 days. Run via background job.
func (q *Queries) PurgeOldAccessLogs(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, purgeOldAccessLogs, dollar_1)
	return err
}

const revokeComponentCertificate = `-- name: RevokeComponentCertificate :one
UPDATE component_certificates
SET revoked_at    = now(),
    revoke_reason = $2
WHERE id          = $1
  AND revoked_at  IS NULL
RETURNING id, org_id, component_type, component_id, ca_id, cert_pem, serial_number, subject, san, issued_at, expires_at, revoked_at, revoke_reason, rotation_of, created_at
`

type RevokeComponentCertificateParams struct {
	ID           uuid.UUID   `json:"id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeComponentCertificate(ctx context.Context, arg RevokeComponentCertificateParams) (ComponentCertificate, error) {
	row := q.db.QueryRow(ctx, revokeComponentCertificate, arg.ID, arg.RevokeReason)
	var i ComponentCertificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ComponentType,
		&i.ComponentID,
		&i.CaID,
		&i.CertPem,
		&i.SerialNumber,
		&i.Subject,
		&i.San,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RotationOf,
		&i.CreatedAt,
	)
	return i, err
}
