// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUserSessionsByGateway = `-- name: CountActiveUserSessionsByGateway :one
SELECT COUNT(*)::bigint AS active_count FROM user_sessions
WHERE gateway_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
  AND revoked_at IS NULL
`

func (q *Queries) CountActiveUserSessionsByGateway(ctx context.Context, gatewayID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUserSessionsByGateway, gatewayID)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const createUserSessionForGateway = `-- name: CreateUserSessionForGateway :one
INSERT INTO user_sessions (org_id, user_id, gateway_id, user_email, expires_at, issued_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, org_id, user_id, gateway_id, issued_at, expires_at, revoked_at, user_email
`

type CreateUserSessionForGatewayParams struct {
	OrgID     uuid.UUID          `json:"org_id"`
	UserID    uuid.UUID          `json:"user_id"`
	GatewayID uuid.UUID          `json:"gateway_id"`
	UserEmail string             `json:"user_email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSessionForGateway(ctx context.Context, arg CreateUserSessionForGatewayParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSessionForGateway,
		arg.OrgID,
		arg.UserID,
		arg.GatewayID,
		arg.UserEmail,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.GatewayID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserEmail,
	)
	return i, err
}

const getUserActiveSession = `-- name: GetUserActiveSession :many
SELECT sessions.id, sessions.org_id, sessions.user_id, sessions.gateway_id, sessions.issued_at, sessions.expires_at, sessions.revoked_at, sessions.user_email FROM user_sessions as sessions
WHERE org_id     = $1::uuid
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
  AND ($3::uuid IS NULL OR gateway_id = $3::uuid)
  AND ($4::text IS NULL OR user_email ILIKE '%' || $4::text || '%')
  AND expires_at > NOW()
  AND revoked_at IS NULL
ORDER BY issued_at DESC
`

type GetUserActiveSessionParams struct {
	OrgID     uuid.UUID   `json:"org_id"`
	UserID    pgtype.UUID `json:"user_id"`
	GatewayID pgtype.UUID `json:"gateway_id"`
	UserEmail pgtype.Text `json:"user_email"`
}

// JOIN gateways ON sessions.gateway_id = gateways.id
func (q *Queries) GetUserActiveSession(ctx context.Context, arg GetUserActiveSessionParams) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, getUserActiveSession,
		arg.OrgID,
		arg.UserID,
		arg.GatewayID,
		arg.UserEmail,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.GatewayID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionByID = `-- name: GetUserSessionByID :one
SELECT id, org_id, user_id, gateway_id, issued_at, expires_at, revoked_at, user_email FROM user_sessions
WHERE id = $1
`

func (q *Queries) GetUserSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.GatewayID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserEmail,
	)
	return i, err
}

const revokeActiveUserSession = `-- name: RevokeActiveUserSession :one
UPDATE user_sessions
SET revoked_at = now()
WHERE id    = $1
  AND expires_at > NOW()
  AND revoked_at IS NULL
RETURNING id, org_id, user_id, gateway_id, issued_at, expires_at, revoked_at, user_email
`

func (q *Queries) RevokeActiveUserSession(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, revokeActiveUserSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.GatewayID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserEmail,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :many
UPDATE user_sessions
SET revoked_at = now()
WHERE user_id    = $1
  AND org_id     = $2
  AND expires_at > NOW()
  AND revoked_at IS NULL
RETURNING id, org_id, user_id, gateway_id, issued_at, expires_at, revoked_at, user_email
`

type RevokeAllUserSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, revokeAllUserSessions, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.GatewayID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
