syntax = "proto3";

package proto;

option go_package = "github.com/JohnnyAsh-U/ashrix-api/proto/ashrix-connector.proto;proto";

import "google/protobuf/timestamp.proto";

// =============================================================================
// Connecotor Bootstrap Proto Types
// =============================================================================

message ConnectorEnrollRequest {
  string                    token     = 1;
  string                    csr_pem   = 2;
  google.protobuf.Timestamp timestamp = 3;
}

message ConnectorEnrollResponse {
  string                    connector_id = 1;
  string                    certificate  = 2;
  string                    trust_bundle = 3;
  google.protobuf.Timestamp expires_at   = 4;
}

message ConnectorRenewCertRequest {
  string                    connector_id = 1;
  string                    signature    = 2;
  string                    csr_pem      = 3;
  google.protobuf.Timestamp timestamp    = 4;
}

message ConnectorRenewCertResponse {
  string                    connector_id = 1;
  string                    certificate  = 2;
  string                    trust_bundle = 3;
  google.protobuf.Timestamp expires_at   = 4;
}

message ConnectorStatusResponse {
  string                 connector_id = 1;
  string                 gateway_id   = 2;
  string                 gateway_url  = 3;
  string                 gateway_ip   = 4;
  string                 tenant_id   = 5;
  repeated ConnectorApps apps         = 6;
}

message ConnectorApps {
  string id          = 1;
  string name        = 2;
  string subdomain   = 3;
  string upstream    = 4; //must be host:port
  string protocol    = 5;
  bool   is_public   = 6;
}

//=================================================================================
//    Tunnel Service
//===========================================================================================
//Each Tunnel call = one proxied Http Request stream
//Connector preopens streams signalling ready and Gateway sends request into a waiting stream
service TunnelService {
  rpc Tunnel(stream TunnelChunk) returns (stream TunnelChunk);
}

message TunnelChunk {
  oneof payload {
    bool           ready      = 1;
    RequestHeader  req_header = 2;
    bytes          body_chunk = 3;
    ResponseHeader res_header = 4;
    bool           end_stream = 5;
  }
}

message RequestHeader {
  string              app_id      = 1;
  string              method      = 2;
  string              path        = 3;
  string              query       = 4;
  map<string, string> headers     = 5;
  string              user_id     = 6;
  string              user_email  = 7;
  string              request_id  = 8;
  int64              body_length = 9;
}

message ResponseHeader {
  int32               status_code = 1;
  map<string, string> headers     = 2;
}

//====================================================================================
//  Management Service to gateway
//==========================================================================================
//Sends Heartbeat to gateway, send hello to gateway
service ConnectorService {
  rpc Connect(stream ConnectorGatewayEnvelope) returns (stream GatewayConnectorEnvelope);
}

message ConnectorGatewayEnvelope {
  string                    connector_id = 1;
  google.protobuf.Timestamp sent_at      = 2;

  oneof payload {
    ConnectorHello     hello     = 3;
    ConnectorHeartbeat heartbeat = 4;
  }
}

message GatewayConnectorEnvelope {

  oneof payload {
    ConnectorHelloAck hello_ack = 1;
    ConnectorReject   reject    = 2;
    ConnectorCmd      cmd       = 3;
  }
}

message ConnectorCmd {
  string cmd     = 1;
  string payload = 2;
}

message ConnectorHello {
  string          connector_id = 1;
  string          tenant_id = 2;
  string          version      = 3;
  repeated ConnectorApps apps         = 4;
  string          transport    = 5; //quic, grpc, websocket
}

message ConnectorHeartbeat {
  int64  seq              = 1;
  string tunnel_state     = 2;
  string tunnel_transport = 3;
  int64  active_streams   = 4;
  int64  uptime_seconds   = 5;
}

message ConnectorHelloAck {
  string session_id     = 1;
  string server_version = 2;
}

message ConnectorReject {
  string reason    = 1;
  string code      = 2;
  bool   permanent = 3;
}

