syntax = "proto3";

package proto;

option go_package = "github.com/JohnnyAsh-U/ashrix-api/proto/ashrix-connector.proto;proto";

import "google/protobuf/timestamp.proto";

// =============================================================================
// Connecotor Bootstrap Proto Types
// =============================================================================

message ConnectorEnrollRequest {
  string                    token     = 1;
  string                    csr_pem   = 2;
  google.protobuf.Timestamp timestamp = 3;
}

message ConnectorEnrollResponse {
  string                    connector_id = 1;
  string                    certificate  = 2;
  string                    trust_bundle = 3;
  bool                      open_sock    = 4;
  google.protobuf.Timestamp expires_at   = 5;
}

message ConnectorRenewCertRequest {
  string                    connector_id = 1;
  string                    signature    = 2;
  string                    csr_pem      = 3;
  google.protobuf.Timestamp timestamp    = 4;
}

message ConnectorRenewCertResponse {
  string                    connector_id = 1;
  string                    certificate  = 2;
  string                    trust_bundle = 3;
  bool                      open_sock    = 4;
  google.protobuf.Timestamp expires_at   = 5;
}

message ConnectorStatusResponse {
  string                 connector_id = 1;
  string                 gateway_id   = 2;
  string                 gateway_url  = 3;
  string                 gateway_ip   = 4;
  string                 tenant_id    = 5;
  bool                   open_sock    = 6;
  repeated ConnectorApps apps         = 7;
}

message ConnectorApps {
  string id        = 1;
  string name      = 2;
  string subdomain = 3;
  string upstream  = 4; //must be host:port
  string protocol  = 5;
  bool   is_public = 6;
  string sock_pass = 7;
}

// =============================================================================
// StreamRequest Proto Types
// =============================================================================

// 1. Wrapper for map[string][]string
message HeaderList {
  repeated string values = 1;
}

// 2. FrameType Enum
enum RequestType {
  UNSPECIFIED_REQUEST = 0;
  HTTP_REQUEST        = 1;
  WS_REQUEST          = 3;
}

enum FlowType {
  UNSPECIFIED_TYPE = 0;
  APP_TO_APP       = 1;
  USER_TO_APP      = 2;
}

// 3. Payload Messages

message StreamFrame {
  string                  request_id     = 1;
  string                  session_id     = 2;
  string                  tenant_id      = 3;
  string                  user_id        = 4;
  string                  user_email     = 5;
  string                  connector_id   = 6;
  string                  app_id         = 7;
  string                  method         = 8;
  string                  host           = 9;
  string                  path           = 10;
  string                  query          = 11;
  map<string, HeaderList> headers        = 12;
  int64                   body_length    = 13;
  RequestType             stream_type    = 14;
  FlowType                flow_type      = 15;
  string                  socks_username = 16;
  string                  socks_password = 17;
}

//====================================================================================
//  Management Service to gateway
//==========================================================================================
//Sends Heartbeat to gateway, send hello to gateway
service ConnectorService {
  //GRPC Tunnel
  rpc Connect(stream ConnectorGatewayEnvelope) returns (stream GatewayConnectorEnvelope);
}

message ConnectorGatewayEnvelope {
  string                    connector_id = 1;
  google.protobuf.Timestamp sent_at      = 2;

  oneof payload {
    ConnectorHello     hello     = 3;
    ConnectorHeartbeat heartbeat = 4;
  }
}

message GatewayConnectorEnvelope {

  oneof payload {
    ConnectorHelloAck hello_ack = 1;
    ConnectorReject   reject    = 2;
    ConnectorCmd      cmd       = 3;
  }
}

message ConnectorCmd {
  CommandType cmd     = 1;
  string      payload = 2;
}

enum CommandType {
  CMD_UNSPECIFIED           = 0;
  CMD_ROTATE_CONNECTOR_CERT = 1;
  CMD_REVOKE_CONNECTOR_CERT = 2;
  CMD_REVOKE_CONNECTOR      = 3;
  CMD_RELOAD_CONNECTOR      = 4;
}

message ConnectorHello {
  string                 connector_id = 1;
  string                 tenant_id    = 2;
  string                 version      = 3;
  repeated ConnectorApps apps         = 4;
  string                 transport    = 5; //quic, grpc, websocket
}

message ConnectorHeartbeat {
  int64  seq              = 1;
  string tunnel_state     = 2;
  string tunnel_transport = 3;
  int64  active_streams   = 4;
  int64  uptime_seconds   = 5;
}

message ConnectorHelloAck {
  string session_id     = 1;
  string server_version = 2;
}

message ConnectorReject {
  string reason    = 1;
  string code      = 2;
  bool   permanent = 3;
}

// message Heartbeat {
//   NodeIdentity identity            = 1; // full state snapshot — CP needs no separate query
//   int32        active_connections  = 2; // live connections (connectors + clients)
//   int32        active_sessions     = 3; // authenticated sessions
//   int32        connector_count     = 4; // how many connectors currently connected
//   repeated ConnectorsStatuses connector_status = 5;
// }

// message ConnectorsStatuses {
//   string                    connector_id = 1;
//   string                    status       = 2; //connected | disconnected
//   google.protobuf.Timestamp last_checked = 3;
// }
